<?php
// --- AUTOGENERATED ---
// database configuration
$db_name = '{$db_name}';			// database name
$db_hostname = '{$db_hostname}';	// database host (usually 'localhost')
$db_username = '{$db_username}';	// database username
$db_password = '{$db_passwd}';		// database password
$db_prefix = '{$db_prefix}';		// database password
$qe_hash_key = '{$qe_hash_key}';	// hash key
$qe_admin_folder = 'admin';			// admin folder, eg: https://www.myweb.tld/[admin], you can change it to improve security

// To rename your administrator ACP folder:
// 1. rename the folder /admin to something, eg /myadmin
// 2. enter the new name to $qe_admin_folder above, eg: 'myadmin'
// 3. save, you are done!
?>