SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

DROP TABLE IF EXISTS `__PREFIX__cache`;
CREATE TABLE `__PREFIX__cache` (
  `cache_id` varchar(255) NOT NULL,
  `cache_value` mediumtext NOT NULL,
  `cache_manual` enum('0','1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`cache_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='qEngine Cache';


DROP TABLE IF EXISTS `__PREFIX__config`;
CREATE TABLE `__PREFIX__config` (
  `idx` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `group_id` varchar(255) NOT NULL,
  `config_id` varchar(255) NOT NULL DEFAULT '',
  `config_value` varchar(255) NOT NULL,
  PRIMARY KEY (`idx`),
  KEY `config_id` (`config_id`),
  KEY `group_id` (`group_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='qEngine Configuration';

INSERT INTO `__PREFIX__config` (`idx`, `group_id`, `config_id`, `config_value`) VALUES
(1, '', 'site_url', '__SITE__'),
(2, '', 'abs_path', ''),
(3, '', 'site_name',  'Demo Site'),
(4, '', 'site_slogan',  'Be Unique. Be Different.'),
(5, '', 'site_description', 'Another site powered by qEngine'),
(6, '', 'site_keywords',  'qengine,cms,c97'),
(7, '', 'site_email', 'admin@admin.com'),
(8, '', 'site_mobile',  'N/A'),
(9, '', 'num_decimals', '2'),
(10,  '', 'num_dec_point',  '.'),
(11,  '', 'num_thousands_sep',  ','),
(12,  '', 'num_currency', '$'),
(13,  '', 'num_curr_pos', '0'),
(14,  '', 'enable_gzip',  '0'),
(15,  '', 'adp_extension',  'php'),
(16,  '', 'enable_adp', '0'),
(17,  '', 'skin', 'skins/default'),
(18,  '', 'list_ipp', '20'),
(19,  '', 'wysiwyg',  '1'),
(20,  '', 'gd_library', '2'),
(21,  '', 'thumb_size', '250'),
(22,  '', 'thumb_quality',  '80'),
(23,  '', 'optimizer',  '80'),
(24,  '', 'multi_lang', '0'),
(25,  '', 'site_start', '2017-08-24'),
(26,  '', 'last_autoexec',  '2017-08-24'),
(27,  '', 'site_fax', '555-123'),
(28,  '', 'site_phone', '555-321'),
(29,  '', 'site_country', 'United States'),
(30,  '', 'site_state', 'Somewhere'),
(31,  '', 'close_site', '0'),
(32,  '', 'weight_name',  'kg'),
(33,  '', 'bbcode', ''),
(34,  '', 'site_address', 'Somestreet No 97'),
(35,  '', 'site_address2',  ''),
(36,  '', 'site_city',  'Somecity'),
(37,  '', 'site_zip', '90210'),
(38,  '', 'user_activation',  '0'),
(39,  '', 'mailog', '1'),
(40,  '', 'num_curr_name',  'USD'),
(41,  '', 'qe_version', '16.1.0/20170824'),
(42,  '', 'company_logo', 'somecompanylogo.png'),
(43,  '', 'favicon',  'somefavicon.png'),
(44,  '', 'cache',  '3600'),
(45,  '', 'allowed_file', 'jpg,jpeg,bmp,gif,png,pcx,zip,7z,doc,xls,ppt,txt,ico'),
(46,  '', 'debug_mode', '0'),
(47,  '', 'disable_browser_cache',  '0'),
(48,  '', 'smtp_email', '0'),
(49,  '', 'smtp_secure',  'ssl'),
(50,  '', 'smtp_server',  'smtp.example.com'),
(51,  '', 'smtp_port',  '465'),
(52,  '', 'smtp_user',  'mymail@example.com'),
(53,  '', 'smtp_passwd',  'mypwd'),
(54,  '', 'smtp_sender',  'mymail@example.com'),
(55,  '', 'enable_module_engine', '1'),
(56,  '', 'enable_module_man',  '1'),
(57,  '', 'enable_qadmin_log',  '1'),
(58,  '', 'enable_detailed_log',  '0'),
(59,  '', 'mobile_version', '0'),
(60,  '', 'default_lang', 'en'),
(61,  '', 'cat_separator',  '&bull;'),
(62,  '', 'facebook_like',  '1'),
(63,  '', 'facebook_comment', '0'),
(64,  '', 'twitter_share',  '1'),
(65,  '', 'allow_locked_page_list', '1'),
(66,  '', 'watermark_file', ''),
(67,  '', 'watermark_position', 'BR'),
(68,  '', 'gmap_api', ''),
(69,  'ke', 'featured_listing', ''),
(70,  'ke', 'guess_allow_submission', '1'),
(71,  'ke', 'guess_confirm_submission', '1'),
(72,  'ke', 'member_confirm_submission',  '0'),
(73,  'ke', 'add_admin_only', '0'),
(74,  'ke', 'ke_version', '3.2/20170909'),
(75,  'ke', 'backlink_code',  '<a href=\"__SITE__/index.php?[user_id]\">Demo Site - Be Different, Be Unique</a>'),
(76,  'ke', 'backlink_autocheck', '1'),
(77,  'ke', 'update_point', '900'),
(78,  'ke', 'update_multiplier',  '10'),
(79,  'ke', 'referral_multiplier',  '3'),
(80,  'ke', 'rating_multipier', '1'),
(81,  'mod_qstats', 'stats_last_update',  '2017-09-03'),
(82,  'mod_pay_paypal', 'ipn',  '1'),
(83,  'mod_pay_paypal', 'sandbox',  '0'),
(84,  'mod_pay_paypal', 'currency_code',  'USD'),
(85,  'mod_pay_bank', 'bankname', 'My Bank'),
(86,  'mod_pay_bank', 'bankaddress',  ''),
(87,  'mod_pay_bank', 'bankcode', 'Bank code (BIC/IBAN/SWIFT)'),
(88,  'mod_pay_bank', 'account',  '1234567890'),
(89,  'mod_pay_bank', 'holder', 'My Name'),
(90,  'mod_pay_cheque', 'recipient',  'My Name'),
(91,  'mod_pay_paypal', 'bussiness',  'seller@c97.net'),
(92,  'mod_pay_paypal', 'conversion_rate',  ''),
(93,  'mod_pay_paypal', 'direct_approval',  '1'),
(94,  'permisi',  'manage_menu',  'a:6:{i:0;s:0:\"\";i:1;s:0:\"\";i:2;s:0:\"\";i:3;s:1:\"1\";i:4;s:1:\"1\";i:5;s:1:\"1\";}'),
(95,  'permisi',  'manage_module',  'a:6:{i:0;s:0:\"\";i:1;s:0:\"\";i:2;s:0:\"\";i:3;s:1:\"1\";i:4;s:1:\"1\";i:5;s:1:\"1\";}'),
(96,  'permisi',  'manage_user',  'a:6:{i:0;s:0:\"\";i:1;s:0:\"\";i:2;s:0:\"\";i:3;s:1:\"1\";i:4;s:1:\"1\";i:5;s:1:\"1\";}'),
(97,  'permisi',  'page_download',  'a:6:{i:0;s:1:\"1\";i:1;s:1:\"1\";i:2;s:1:\"1\";i:3;s:1:\"1\";i:4;s:1:\"1\";i:5;s:1:\"1\";}'),
(98,  'permisi',  'page_editor',  'a:6:{i:0;s:0:\"\";i:1;s:1:\"1\";i:2;s:1:\"1\";i:3;s:1:\"1\";i:4;s:1:\"1\";i:5;s:1:\"1\";}'),
(99,  'permisi',  'page_manager', 'a:6:{i:0;s:0:\"\";i:1;s:0:\"\";i:2;s:1:\"1\";i:3;s:1:\"1\";i:4;s:1:\"1\";i:5;s:1:\"1\";}'),
(100, 'permisi',  'permisi',  'a:6:{i:0;s:0:\"\";i:1;s:0:\"\";i:2;s:0:\"\";i:3;s:0:\"\";i:4;s:0:\"\";i:5;s:1:\"1\";}'),
(101, 'permisi',  'site_config',  'a:6:{i:0;s:0:\"\";i:1;s:0:\"\";i:2;s:0:\"\";i:3;s:0:\"\";i:4;s:0:\"\";i:5;s:1:\"1\";}'),
(102, 'permisi',  'site_setting', 'a:6:{i:0;s:0:\"\";i:1;s:0:\"\";i:2;s:0:\"\";i:3;s:0:\"\";i:4;s:1:\"1\";i:5;s:1:\"1\";}'),
(103, 'permisi',  'site_log', 'a:6:{i:0;s:0:\"\";i:1;s:0:\"\";i:2;s:0:\"\";i:3;s:0:\"\";i:4;s:1:\"1\";i:5;s:1:\"1\";}'),
(104, 'permisi',  'site_file',  'a:6:{i:0;s:0:\"\";i:1;s:0:\"\";i:2;s:0:\"\";i:3;s:0:\"\";i:4;s:1:\"1\";i:5;s:1:\"1\";}');

DROP TABLE IF EXISTS `__PREFIX__ip_log`;
CREATE TABLE `__PREFIX__ip_log` (
  `idx` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `log_time` int(10) unsigned NOT NULL DEFAULT '0',
  `log_ip_addr` varchar(45) NOT NULL DEFAULT '',
  `log_user_id` varchar(80) NOT NULL DEFAULT '',
  `log_user_type` char(1) NOT NULL DEFAULT 'U',
  `log_success` char(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`idx`),
  KEY `log_user_type` (`log_user_type`),
  KEY `log_ip_addr` (`log_ip_addr`),
  KEY `log_user_id` (`log_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `__PREFIX__language`;
CREATE TABLE `__PREFIX__language` (
  `lang_id` char(2) NOT NULL,
  `lang_key` varchar(255) NOT NULL,
  `lang_value` text NOT NULL,
  KEY `lang_id` (`lang_id`),
  KEY `lang_key` (`lang_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `__PREFIX__language` (`lang_id`, `lang_key`, `lang_value`) VALUES
('en',	'_config:lang_name',	'English'),
('en',	'_config:cache',	''),
('en',	'_config:enabled',	'1'),
('en',	'l_long_date_format',	'l, F-d-Y'),
('en',	'l_short_date_format',	'M-d-Y'),
('en',	'l_select_date_format',	'MDY'),
('en',	'l_language_short',	'en-us'),
('en',	'l_encoding',	'utf-8'),
('en',	'l_mysql_encoding',	'utf8'),
('en',	'l_direction',	'ltr'),
('en',	'l_ok',	'Ok'),
('en',	'l_submit',	'Submit'),
('en',	'l_enter_captcha',	'Type the characters into the box:'),
('en',	'l_captcha_error',	'Invalid Captcha'),
('en',	'l_guest',	'Guest'),
('en',	'l_date',	'Date'),
('en',	'l_title',	'Title'),
('en',	'l_yes',	'Yes'),
('en',	'l_no',	'No'),
('en',	'l_up',	'Up'),
('en',	'l_down',	'Down'),
('en',	'l_left',	'Left'),
('en',	'l_right',	'Right'),
('en',	'l_top',	'Top'),
('en',	'l_bottom',	'Bottom'),
('en',	'l_back',	'Back'),
('en',	'l_never',	'Never'),
('en',	'l_none',	'None'),
('en',	'l_na_select',	'n/a'),
('en',	'l_all',	'All'),
('en',	'l_all_cat',	'All Categories'),
('en',	'l_untitled',	'Untitled'),
('en',	'l_no_description',	'No description.'),
('en',	'l_pp_top',	'First'),
('en',	'l_pp_last',	'Last'),
('en',	'l_pp_next',	'&raquo;'),
('en',	'l_pp_prev',	'&laquo;'),
('en',	'l_item',	'item'),
('en',	'l_items',	'items'),
('en',	'l_page',	'page'),
('en',	'l_pages',	'pages'),
('en',	'l_print',	'Print This Page'),
('en',	'l_downloading',	'Downloading'),
('en',	'l_download_click',	'Click the link if download does not start automatically.'),
('en',	'l_browser_back_button',	'Please use your browser <a href=\"javascript:history.go(-1)\">&lt;back&gt;</a> button to return to previous page!'),
('en',	'l_open_url',	'<a href=\"%1$s\"><img src=\"../skins/_admin/images/url.gif\" border=\"0\" alt=\"Open Link\" /> %2$s</a>'),
('en',	'l_demo_mode',	'<p align=\"center\">Demo mode, you can\'t upload files in demo mode!</p>'),
('en',	'l_site_closed_info',	'<h1>Site Closed</h1><p>Thank you for coming to our website. It has been temporarily closed while we are updating it. Please come back again soon.</p><p>The website administrator can login to see the web site.</p>'),
('en',	'l_login',	'Login'),
('en',	'l_login_register',	'Login/Register'),
('en',	'l_logout',	'Log Out'),
('en',	'l_login_why',	'Enter your username &amp; password to log in.'),
('en',	'l_you_are_not_login',	'You are not logged in.'),
('en',	'l_you_are_login',	'You are logged in as'),
('en',	'l_username',	'Username'),
('en',	'l_password',	'Password'),
('en',	'l_lost_passwd',	'Lost Password'),
('en',	'l_reset_passwd',	'Reset Password'),
('en',	'l_reset_code',	'Reset Code'),
('en',	'l_account_act',	'Account Activation'),
('en',	'l_account_act_why',	'All new members must activate their account before logging in.'),
('en',	'l_account_act_key',	'Activation Key'),
('en',	'l_account_act_key_why',	'You will find the key, in the email we sent to you.'),
('en',	'l_contact_us',	'Contact Us'),
('en',	'l_contact_us_form',	'Fill in this form to send us a message.'),
('en',	'l_register',	'Register'),
('en',	'l_register_now',	'Register Now'),
('en',	'l_email_address',	'Email Address'),
('en',	'l_current_password',	'Current Password'),
('en',	'l_new_password',	'New Password'),
('en',	'l_confirm_password',	'Confirm New Password'),
('en',	'l_subscribe_newsletter',	'Subscribe to our free newsletter'),
('en',	'l_subscribe',	'Subscribe'),
('en',	'l_unsubscribe',	'Unsubscribe'),
('en',	'l_username_used',	'In use! Please choose another username'),
('en',	'l_email_used',	'Please choose a different email address'),
('en',	'l_name_empty',	'Please give us your name'),
('en',	'l_message_empty',	'No message was entered'),
('en',	'l_username_error',	'Invalid username'),
('en',	'l_email_error',	'Invalid email'),
('en',	'l_password_empty',	'Incorrect password'),
('en',	'l_password_error',	'Password Error!'),
('en',	'l_account',	'Account'),
('en',	'l_my_account',	'My Account'),
('en',	'l_manage_profile',	'Manage Profile'),
('en',	'l_manage_profile_why',	'Manage your email &amp; password.'),
('en',	'l_manage_subscription',	'Manage Subscription'),
('en',	'l_manage_subscription_why',	'Manage your subscription to our newsletter, email reminders and more.'),
('en',	'l_manage_faq',	'Knowledge Center/FAQ'),
('en',	'l_manage_faq_why',	'Do you have a problem or question? Please visit our knowledge center and if you still cannot find an answer, you can also contact us.'),
('en',	'l_manage_logout_why',	'Logout from your account. It\'s highly recommended to logout after each transaction, especially on a public computer.'),
('en',	'l_profile_enter_passwd',	'Enter your current password, in order to change your password or email address'),
('en',	'l_passwd_changed_subject',	'Your password has been changed!'),
('en',	'l_newsletter_subscribed',	'You are currently subscribed to our newsletter'),
('en',	'l_newsletter_unsubscribed',	'You are currently not subscribed to our newsletter'),
('en',	'l_passwd_not_entered',	'Password not entered'),
('en',	'l_tell_friend',	'Share this site'),
('en',	'l_your_name',	'Your Name'),
('en',	'l_your_email',	'Your Email'),
('en',	'l_subject',	'Subject'),
('en',	'l_message',	'Message'),
('en',	'l_friend_name',	'Friend\'s Name'),
('en',	'l_friend_email',	'Friend\'s Email'),
('en',	'l_newsletter',	'Newsletter'),
('en',	'l_search',	'Search'),
('en',	'l_site_search',	'Site Search'),
('en',	'l_content_search',	'Content Search'),
('en',	'l_quick_search',	'Search in title only (quick search)'),
('en',	'l_search_result',	'Search Results'),
('en',	'l_contents',	'Contents'),
('en',	'l_more_result',	'More Results'),
('en',	'l_search_no_result',	'Sorry, we could not find what your were looking for. Please try refining your search terms, or contact us for assistance.'),
('en',	'l_you_are_here',	'You are here'),
('en',	'l_downloaded',	'downloaded'),
('en',	'l_page_gallery',	'Gallery'),
('en',	'l_posted_by',	'Posted By'),
('en',	'l_posted_on',	'Posted On'),
('en',	'l_last_updated',	'Last Updated'),
('en',	'l_related_page',	'Related Pages'),
('en',	'l_article_by',	'Articles by'),
('en',	'l_other_cat',	'Other Categories'),
('en',	'l_page_author',	'Author'),
('en',	'l_comment_helpful',	'%1$s of %2$s people found this comment to be helpful'),
('en',	'l_conc_num',	'There are %1$s replies to this comment'),
('en',	'l_conc_non',	'Reply to this'),
('en',	'l_comment',	'Comments'),
('en',	'l_facebook_comment',	'Facebook Comments'),
('en',	'l_no_comment',	'There is no comment. Why not be the first?'),
('en',	'l_one_comment',	'There is one comment. Why not be the second?'),
('en',	'l_more_comment',	'There are %1$s comments. Why not add your own?'),
('en',	'l_mail_us_subject',	'Subject'),
('en',	'l_mail_register',	'Your account at %1$s'),
('en',	'l_mail_friend_subject',	'Your friend wanted to show you a website that you might be interested in'),
('en',	'l_mail_lost_subject',	'Your password at %1$s'),
('en',	'datetime.Sunday',	'Sunday'),
('en',	'datetime.Monday',	'Monday'),
('en',	'datetime.Tuesday',	'Tuesday'),
('en',	'datetime.Wednesday',	'Wednesday'),
('en',	'datetime.Thursday',	'Thursday'),
('en',	'datetime.Friday',	'Friday'),
('en',	'datetime.Saturday',	'Saturday'),
('en',	'datetime.Sun',	'Sun'),
('en',	'datetime.Mon',	'Mon'),
('en',	'datetime.Tue',	'Tue'),
('en',	'datetime.Wed',	'Wed'),
('en',	'datetime.Thu',	'Thu'),
('en',	'datetime.Fri',	'Fri'),
('en',	'datetime.Sat',	'Sat'),
('en',	'datetime.January',	'January'),
('en',	'datetime.February',	'February'),
('en',	'datetime.March',	'March'),
('en',	'datetime.April',	'April'),
('en',	'datetime.May',	'May'),
('en',	'datetime.June',	'June'),
('en',	'datetime.July',	'July'),
('en',	'datetime.August',	'August'),
('en',	'datetime.September',	'September'),
('en',	'datetime.October',	'October'),
('en',	'datetime.November',	'November'),
('en',	'datetime.December',	'December'),
('en',	'datetime.Jan',	'Jan'),
('en',	'datetime.Feb',	'Feb'),
('en',	'datetime.Mar',	'Mar'),
('en',	'datetime.Apr',	'Apr'),
('en',	'datetime.Jun',	'Jun'),
('en',	'datetime.Jul',	'Jul'),
('en',	'datetime.Aug',	'Aug'),
('en',	'datetime.Sep',	'Sep'),
('en',	'datetime.Oct',	'Oct'),
('en',	'datetime.Nov',	'Nov'),
('en',	'datetime.Dec',	'Dec'),
('en',	'l_all_news',	'All News'),
('en',	'l_site_news',	'Site Announcements'),
('en',	'msg.can_not_upload',	'<h1>Not Allowed!</h1>\r\n<p>You are trying to upload restricted files, or site in demo mode. Upload has been cancelled!</p>'),
('en',	'msg.no_cat_list',	'<h1>Not Allowed!</h1>\r\n<p>You are not allowed to see the page list!</p>'),
('en',	'msg.mod_install_ok',	'<h1>Installation Complete</h1>\r\n<p>You may need to <a href=\"#\" onclick=\"top.location.reload(true)\">refresh your browser</a> to display the new module menu.</p>'),
('en',	'msg.mod_uninstall_ok',	'<h1>Uninstalled</h1>\r\n<p>You may need to <a href=\"#\" onclick=\"top.location.reload(true)\">refresh browser</a> to remove module menu.<br />You may also need to remove some files/folders manually.</p>'),
('en',	'msg.no_config',	'<h1>No Configurable Options</h1>\r\n<p>This module/plugin has no options that you can configure.</p>'),
('en',	'msg.cache',	'<h1>Please Rebuild System Cache</h1>\r\n<p>If you have made some changes, then you should <a href=\"cache.php\"> rebuild your system cache</a>. This makes your site run more efficiently.</p>'),
('en',	'msg.tpl_only',	'<h1>Cannot Open File!</h1>\r\n<p>You are about to open a file that is not a recognized skin-file. (*.tpl) files are skin files and are used to make your site look as it does.</p>'),
('en',	'msg.sa_only',	'<h1>Whoops!</h1>\r\n<p>This feature is for administrators only!</p>'),
('en',	'msg.no_level',	'<h1>You Don\'t Have Permission!</h1>\r\n<p>This feature requires that you have a higher administrator level.</p>'),
('en',	'msg.qadmin_email_ok',	'<h1>Complete!</h1>\r\n<p>Your changes have been saved. An email has also been sent to your address with form values.</p>'),
('en',	'msg.qadmin_required_err',	'<h1>Empty Fields!</h1>\r\n<p>Please fill the following: %1$s</p>'),
('en',	'msg.admin_err',	'<h1>FAILED!</h1>\r\n<p>Something is wrong. Make sure that you have filled all required fields, and try again.</p>'),
('en',	'msg.admin_error',	'<h1>FAILED!</h1>\r\n<p>Something is wrong. Make sure that you have filled all required fields, and try again.</p>'),
('en',	'msg.ok',	'<h1>Complete!</h1>\r\n<p>Your changes have been saved</p>'),
('en',	'msg.admin_ok',	'<h1>Complete!</h1>\r\n<p>Your changes have been saved</p>'),
('en',	'msg.email_ok',	'<h1>Email Sent!</h1>\r\n<p>An email has been sent to the recipient.</p>'),
('en',	'msg.reset_error',	'<h1>Password Reset Failed!</h1>\r\n<p>Make sure you have entered valid username, reset code and new password!</p>'),
('en',	'msg.act_error',	'<h1>Activation Failed!</h1>\r\n<p>%1$s</p>'),
('en',	'msg.user_act',	'<h1>User Activation Required!</h1>\r\n<p>We require all new members to activate their account before they can login.<br />Please check your emails for more information and to verify your email address</p>'),
('en',	'msg.contact_err',	'<h1>Can not send the information</h1>\r\n<p>This is why: %1$s</p>'),
('en',	'msg.contact_ok',	'<h1>Complete</h1>\r\n<p>Your message has been sent. Thank you.</p>'),
('en',	'msg.passwd_changed',	'<h1>Password Changed!</h1>\r\n<p>Your password has been changed. You may need to logout of your account and login again.</p>'),
('en',	'msg.register_ok',	'<h1>Congratulation!</h1>\r\n<p>You have been registered in this site successfully!<br />Please enjoy your stay!</p>'),
('en',	'msg.register_error',	'<h1>Register Error!</h1>\r\n<p>Error in: %1$s</p>'),
('en',	'msg.update_error',	'<h1>Profile Error!</h1>\r\n<p>Error in: %1$s</p>'),
('en',	'msg.lost_error',	'<h1>Password Retrieval Failed!</h1>\r\n<p>Your username/email address could not be found in our database.</p>'),
('en',	'msg.lost_ok',	'<h1>Password Retrieval Success!</h1>\r\n<p>An email has been sent to you containing information regarding your username &amp; password. Please check your inbox.</p>'),
('en',	'msg.bad_login',	'<h1>Unable to Login!</h1>\r\n<p>Incorrect username or password. Please try again or contact us for assistance</p>'),
('en',	'msg.ezform_ok',	'<h1>Form Has Been Submitted!</h1>\r\n<p>Thank you!</p>'),
('en',	'msg.ezform_required_err',	'<h1>Form Cannot Be Submitted!</h1>\r\n<p>%1$s</p>'),
('en',	'msg.email_err',	'<h1>Invalid Email Address!</h1>\r\n<p>The email address you just entered does not appear to be valid. Please ensure you have entered it correctly or enter an alternative email address</p>'),
('en',	'msg.unsub_ok',	'<h1>Subscription Changes Made!</h1>\r\n<p>Your email address has now been removed from our database and you will not receive any more correspondence from us.</p>'),
('en',	'msg.sub_ok',	'<h1>Subscription Success!</h1>\r\n<p>Thanks for subscribing to our site. Check your inbox soon for notifications from us.</p>'),
('en',	'msg.site_closed',	'<h1>Temporarily Closed!</h1>\r\n<p>%1$s is temporarily closed as we are updating our site.<br />Please try visiting us again soon!.</p>'),
('en',	'msg.tell_error',	'<h1>Whoops!</h1>\r\n<p>It looks like you missed entering some of the information that was required. Please try again.</p>'),
('en',	'msg.tell_ok',	'<h1>Complete</h1>\r\n<p>An email has been sent to %1$s Thank you.</p>'),
('en',	'msg.demo_mode',	'<h1>Demo Mode!</h1>\r\n<p>Currently running in demo mode.<br />Your changes have not been saved!</p>'),
('en',	'msg.not_member',	'<h1>Members Only!</h1>\r\n<p>This page is for members only! Please login first!</p>'),
('en',	'msg.username_not_found',	'<h1>Username Not Available!</h1>\r\n<p>Username can not be found or is no longer available!</p>'),
('en',	'msg.captcha_error',	'<h1>Invalid Captcha!</h1>\r\n<p>Please enter the number shown on screen correctly!</p>'),
('en',	'msg.sql_error',	'<h1>Database Error</h1>\r\n<p>%1$s</p>'),
('en',	'msg.echo',	'<h1>Notice!</h1>\r\n<p>%1$s</p>'),
('en',	'msg.msg_about',	'<h1>Copyright(c)C97net</h1>\r\n<p>This software is powered by <a href=\"http://www.c97.net\">qEngine</a>Removal of this copyright information or any other credits is strictly prohibited</p>'),
('en',	'msg.default',	'<h1>For your Attention...</h1>\r\n<p>Message ID: %1$s<br /><a href=\"mailto:\">Contact C97net</a> (www.c97.net) for more information</p>'),
('en',	'msg.fman_error',	'<h1>File Manager Error</h1>\r\n<p>Cannot proceed with this request. Please make sure that you have enough privileges.</p>'),
('en',	'msg.module_engine_disabled',	'<h1>Module Error!</h1>\r\n<p>MODULE_ENGINE is disabled!</p>'),
('en',	'msg.module_engine_error',	'<h1>Module Error!</h1>\r\n<p>Module <b>%1$s</b> is disabled or not installed!</p>'),
('en',	'msg.page_attachment_error',	'<h1>Download Failed!</h1>\r\n<p>Attachment is either not available or not found!</p>'),
('en',	'msg.ssl_error',	'<h1>SSL ERROR!</h1>\r\n<p>Your server does not support SSL connection. Please review your configuration</p>'),
('en',	'msg.qcomment_err_1',	'<h1>Comment Error!</h1>\r\n<p>Invalid mod_id, please define it in ACP!</p>'),
('en',	'msg.qcomment_err_2',	'<h1>Comment Error!</h1>\r\n<p>Invalid page title!</p>'),
('en',	'msg.qcomment_err_3',	'<h1>Comment Error!</h1>\r\n<p>You can only comment once for the same item!</p>'),
('en',	'msg.qcomment_err_4',	'<h1>Comment Error!</h1>\r\n<p>Please enter a message!</p>'),
('en',	'msg.qcomment_err_5',	'<h1>Comment Error!</h1>\r\n<p>You have voted for this item!</p>'),
('en',	'msg.qcomment_err_6',	'<h1>Comment Error!</h1>\r\n<p>Invalid rating value!</p>'),
('en',	'msg.qcomment_ok_1',	'<h1>Comment accepted</h1>\r\n<p>We will post it as soon as possible. Thank your for your participation!</p>'),
('en',	'msg.qcomment_ok_2',	'<h1>Vote accepted</h1>\r\n<p>We will post it as soon as possible. Thank your for your participation!</p>'),
('en',	'msg.permalink_error',	'<h1>Page Not Found</h1>\r\n<p>Document %1$s not found. Please contact us for more information.</p>'),
('en',	'msg.fman_copy_err',	'<h1>File Manager Error</h1>\r\n<p>File copy failed!</p>'),
('en',	'msg.fman_move_err',	'<h1>File Manager Error</h1>\r\n<p>File move failed!</p>'),
('en',	'msg.fman_ren_err',	'<h1>File Manager Error</h1>\r\n<p>File rename failed!</p>'),
('en',	'msg.fman_del_err',	'<h1>File Manager Error</h1>\r\n<p>File deletion failed!</p>'),
('en',	'msg.fman_new_err',	'<h1>File Manager Error</h1>\r\n<p>File creation failed</p>'),
('en',	'msg.fman_mkdir_err',	'<h1>File Manager Error</h1>\r\n<p>Make new folder failed!</p>'),
('en',	'msg.fman_rendir_err',	'<h1>File Manager Error</h1>\r\n<p>Folder rename failed</p>'),
('en',	'msg.fman_rmdir_err',	'<h1>File Manager Error</h1>\r\n<p>Folder deletion failed</p>'),
('en',	'msg.fman_not_allowed',	'<h1>File Manager Error</h1>\r\n<p>You are not allowed to do this!</p>'),
('en',	'msg.fman_not_found',	'<h1>File Manager Error</h1>\r\n<p>File not found!</p>'),
('en',	'msg.menuman_locked_err',	'<h1>Menu Manager Error</h1>\r\n<p>This menu is locked by another application. Please use the application to edit this menu!</p>'),
('en',	'msg.mod_not_installed',	'<h1>Uninstallation Failed</h1>\r\n<p>This module has not been installed.</p>'),
('en',	'msg.mod_installed',	'<h1>Installation Failed</h1>\r\n<p>This module has not been installed.</p>'),
('en',	'msg.qadmin_item_not_found',	'<h1>Fatal Error</h1>\r\n<p>Item not found!</p>'),
('en',	'msg.permalink_cfg_error',	'<h1>Fatal Error</h1>\r\n<p>Permalink setting is invalid! See qadmin_demo!</p>'),
('en',	'mail.admin_mail',	'<p><b>Hello {$user_id},</b></p>\r\n\r\n<p>[write your message here]</p>'),
('en',	'mail.change_pwd',	'<p>Hi, {$user_id}<br />\r\nToday, you or someone else has changed your password to:<br />\r\n<b>{$user_passwd}</b></p>\r\n\r\n<p>If you didn\'t make this change, please login to your account immediately, using the above information, and contact us for more information.</p>\r\n\r\n<p>Thank you,<br />\r\n<br />\r\n{$site_name}</p>'),
('en',	'mail.contact',	'<p>You have been sent a message from your website {$l_site_name}.</p>\r\n<hr />\r\n<p>Name: {$name}<br />\r\nEmail: {$email}</p>\r\n\r\n<p>The message:</p>\r\n{$body}'),
('en',	'mail.contact_reply',	'<p>Thank you for contacting us, {$name}.</p>\r\n\r\n<p>We will respond to your enquiry as soon a possible. In the meantime, please visit our website for more information.</p>\r\n\r\n<p>Best regards,<br />\r\n{$title}</p>'),
('en',	'mail.lost',	'<p>Hi,<br />\r\nyou have requested to reset your password at {$site_name}.</p>\r\n\r\n<p>Your username: {$user_id}<br />\r\nYour reset code: {$reset}</p>\r\n\r\n<p>All you have to do is go to\r\n<a href=\"{$site_url}/profile.php?mode=reset&user_id={$user_id}&reset={$reset}\">{$site_url}/profile.php?mode=reset&user_id={$user_id}&reset={$reset}</a>\r\nand you can enter your new password.</p>\r\n\r\n<p>Thank you.</p>'),
('en',	'mail.newsletter',	'<p>ENTER YOUR MESSAGE HERE</p>'),
('en',	'mail.outline',	'<!DOCTYPE html>\r\n<html lang=\"en\">\r\n<head>\r\n  <meta charset=\"{$l_encoding}\" />\r\n  <meta name=\"description\" content=\"{$site_description}\" />\r\n <meta name=\"keywords\" content=\"{$site_keywords}\" />\r\n <meta name=\"author\" content=\"{$site_email}\" />\r\n  <base href=\"{$site_url}/\" />\r\n  <style type=\"text/css\">\r\n body{background:#eee}\r\n th{text-align:left}\r\n *{font-family:Arial,Helvetica,San-serif}\r\n  </style>\r\n</head>\r\n\r\n<body>\r\n <div style=\"max-width:700px;margin:auto\">\r\n   <div>{$company_logo}</div>\r\n    <div style=\"border-top:solid 10px #333; background:#fff; padding:20px\">\r\n   <<main_body>>\r\n   </div>\r\n    <div style=\"color:#888;font-size:8pt\">\r\n      &copy; {$site_name} &mdash; <a href=\"{$site_url}\">{$site_url}</a>, Email: <a href=\"mailto:{$site_email}\">{$site_email}</a>\r\n    </div>\r\n</body>\r\n</html>'),
('en',	'mail.register',	'<p>You are now registered at {$site_name} (<a href=\"{$site_url}\">{$site_url}</a>)</p>\r\n\r\n<p>This email contains your username & password</p>\r\n\r\n<p>Email: {$user_email}<br />\r\n Username: {$user_id}<br />\r\n Password: {$user_passwd}<br />\r\n<!-- BEGINIF $act -->\r\n Activation Code: {$act}</p>\r\n\r\n<p>Our site requires you to activate your account before you can login.</p>\r\n<p>To activate your account, simply go to: <a href=\"{$site_url}/profile.php?mode=act&user_id={$user_id}&act={$act}\">{$site_url}/profile.php?mode=act&user_id={$user_id}&act={$act}</a>\r\n<!-- ENDIF -->\r\n</p>\r\n\r\n<p>Best Regards,<br />\r\n{$site_url}\r\n\r\n<p>If you have never registered at {$site_name}, please contact us.</p>'),
('en',	'mail.tell',	'<p>Hi, {$friend_name},</p>\r\n<p>Your friend, {$name} (email: {$email}) thinks you might be interested in our site.<br />\r\nFor more information, please visit <a href=\"{$site_url}\">{$site_name}</a>.</p>\r\n\r\n<p>Additionally, your friend says:<br />\r\n{$tell_body}</p>\r\n\r\n<p>Best Regards,<br />\r\n{$site_name}</p>'),
('en',	'l_rating_1',	'Poor'),
('en',	'l_rating_2',	'Below Average'),
('en',	'l_rating_3',	'Average'),
('en',	'l_rating_4',	'Above Average'),
('en',	'l_rating_5',	'Excellent'),
('en',	'l_edit',	'Edit'),
('en',	'l_enter_page_number',	'Enter page number'),
('en',	'l_default',	'Default'),
('en',	'l_page_member_only',	'<h1>This page is only available to members, please register/login, in order to read this page!</h1>'),
('en',	'l_page_admin_only',	'<h1>This page is only available to administrators, please login to read this page!</h1>'),
('en',	'l_page_not_found',	'<h1>Page not found!</h1>'),
('en',	'l_page_draft',	'<h1 class=\"well\">This page has not been published, yet!</h1>'),
('en',	'l_review',	'Reviews'),
('en',	'l_toolbox',	'Toolbox'),
('en',	'l_add_favorite',	'Add to Favorite'),
('en',	'l_see_also',	'See Also'),
('en',	'l_description',	'Description'),
('en',	'l_contact_owner',	'Contact Owner'),
('en',	'l_specification',	'Specification'),
('en',	'l_also_by',	'Also By %s'),
('en',	'l_share_item',	'Share This Listing'),
('en',	'l_notify_us',	'Report This Listing'),
('en',	'mail.tell_friend',	'<p>Hi, <b>{$friend_name}</b>,</p><p>Your friend, {$name} (email: {$email}) thinks that you might be interested in a listing in our site.</p>\r\n<p>For more information, visit <a href=\"{$site_url}/{$url}\">{$site_url}/{$url}</a>.</p>\r\n<p style=\"border:solid 1px #999;width:290px; text-align:center; padding:5px\"><b>{$item_title}</b><br />\r\n<a href=\"{$site_url}/{$url}\">{$image}</a><br />\r\n{$item_summary}</p>\r\n<p>Additionally, your friend says:<br />\r\n{$tell_body}</p><p>Best Regards,<br />\r\n{$site_name}<br />\r\n<a href=\"{$site_url}\">{$site_url}</a></p>'),
('en',	'mail.tell_us',	'<p>Hi, <b>site owner</b>,</p><p>A visitor, {$name} (email: {$email}) sent you a message about a listing in your web site of \"{$item_title}\".</p>\r\n<p style=\"border:solid 1px #999;width:290px; text-align:center; padding:5px\"><a href=\"{$site_url}/{$url}\"><b>{$item_title}</b></a><br />\r\n<a href=\"{$site_url}/{$url}\">{$image}</a><br />\r\n{$item_summary}</p>\r\n<p>The message is as follow:<br />\r\n{$tell_body}</p>\r\n<p>To answer this message, please contact the visitor directly.</p>\r\n<p>Best Regards,<br />\r\n{$site_name}<br />\r\n<a href=\"{$site_url}\">{$site_url}</a></p>'),
('en',	'mail.tell_owner',	'<p>Hi, <b>{$owner_email}</b>,</p><p>A visitor, {$name} (email: {$email}) sent you a message about your listing of \"{$item_title}\".</p>\r\n<p style=\"border:solid 1px #999;width:290px; text-align:center; padding:5px\"><a href=\"{$site_url}/{$url}\"><b>{$item_title}</b><br />\r\n<a href=\"{$site_url}/{$url}\">{$image}</a><br />\r\n{$item_summary}</p>\r\n<p>The message is as follow:<br />\r\n{$tell_body}</p>\r\n<p>To answer this message, please contact the visitor directly.</p>\r\n<p>Best Regards,<br />\r\n{$site_name}<br />\r\n<a href=\"{$site_url}\">{$site_url}</a></p>'),
('en',	'l_tell_owner_subject',	'About your listing of %s'),
('en',	'l_tell_us_subject',	'About a listing of %s'),
('en',	'l_title_asc',	'Title Ascending'),
('en',	'l_title_dsc',	'Title Descending'),
('en',	'l_date_asc',	'Date Ascending'),
('en',	'l_date_dsc',	'Date Descending'),
('en',	'l_list',	'List'),
('en',	'l_grid',	'Grid'),
('en',	'l_sort_by',	'Sort By'),
('en',	'l_list_style',	'List Style'),
('en',	'msg.tellus_ok',	'<h1>Complete</h1>\r\n<p>An email has been sent to the website administrator. Thank you.</p>'),
('en',	'msg.tellowner_ok',	'<h1>Complete</h1>\r\n<p>An email has been sent to listing owner. Thank you.</p>'),
('en',	'l_category',	'Category'),
('en',	'l_directory',	'Directory'),
('en',	'l_sponsored',	'Sponsored'),
('en',	'l_premium',	'Premium'),
('en',	'l_regular',	'Regular'),
('en',	'l_rate_asc',	'Rating Ascending'),
('en',	'l_rate_dsc',	'Rating Descending'),
('en',	'l_rating',	'Rating'),
('en',	'l_title_details_err',	'Title and details need to be filled in!'),
('en',	'l_url_err',	'URL must be filled in, or is already in use!'),
('en',	'l_backlink_err',	'Backlink URL must be filled in, or is already in use!'),
('en',	'l_summary_err',	'Summary must be filled in!'),
('en',	'msg.add_error',	'<h1>Add/Edit Listing Error</h1>\r\n<p>Please verify the following errors:</p>\r\n%s'),
('en',	'mail.add_inform_adm',	'<p>There is a new submission for <a href=\"{$site_url}\">{$site_name}</a> as follow:</p>\r\n<p><b>Directory: {$dir_title}</b><br />\r\nTitle: {$item_title}<br />\r\n{$optional_fields}\r\nDetails: {$item_details}</p>\r\n\r\n<p><b>User Information</b><br />\r\nUser ID: {$owner_id}<br />\r\nEmail: {$owner_email}</p>\r\n\r\n<p><b>Custom Fields</b><br />\r\n{$cf_email}</p>\r\n\r\n<p>You can manage this submission from ACP: <a href=\"{$site_url}/admin/listing.php?cmd=edit&item_id={$item_id}\">{$site_url}/admin/listing.php?cmd=edit&item_id={$item_id}</a></p>'),
('en',	'mail.add_inform_usr',	'<h1>Hi!</h1>\r\n<p>Here is the summary of your recent submission for <a href=\"{$site_url}\">{$site_name}</a>:</p>\r\n<p><b>Directory: {$dir_title}</b><br />\r\nTitle: {$item_title}<br />\r\n{$optional_fields}\r\nDetails: {$item_details}</p>\r\n\r\n<p><b>Other Information</b><br />\r\n{$cf_email}</p>\r\n\r\n<p><b>User Information</b><br />\r\nUser ID: {$owner_id}<br />\r\nEmail: {$owner_email}</p>\r\n\r\n<!-- BEGINIF $isLogin -->\r\n<p><b>Manage Your Listings</b><br />\r\nYou can manage, edit or upgrade your listings in your Account Page.</p>\r\n<!-- ELSE -->\r\n<p><b>Password Information</b><br />\r\nItem ID: {$item_id}<br />\r\nEdit Password: {$owner_passwd}<br />\r\nYou should use above information to modify or upgrade your <a href=\"{$site_url}/add.php?cmd=edit_guest\">listing here.</a></p>\r\n<p>Please keep this email for future reference.</p>\r\n<!-- ENDIF -->\r\n\r\n<p>Please wait for our approval. It may take up to 24 hours to approve your submission. Thank you for your patience.</p>\r\n<p>If you have not submited an entry to our web site, please <a href=\"{$site_url}/contact.php\">contact us here</a>.</p>'),
('en',	'mail.add_confirm_usr',	'<h1>Hi!</h1>\r\n<p>Here is the summary of your recent submission for <a href=\"{$site_url}\">{$site_name}</a>:</p>\r\n<p><b>Directory: {$dir_title}</b><br />\r\nTitle: {$item_title}<br />\r\n{$optional_fields}\r\nDetails: {$item_details}</p>\r\n\r\n<p><b>Other Information</b><br />\r\n{$cf_email}</p>\r\n\r\n<p><b>User Information</b><br />\r\nUser ID: {$owner_id}<br />\r\nEmail: {$owner_email}</p>\r\n\r\n<p><b>IMPORTANT!</b></p>\r\n<p>Please <a href=\"{$site_url}/add.php?cmd=confirm&amp;item_id={$item_id}&amp;secret_key={$owner_passwd}\">click here</a> to confirm this submission. If you don\'t confirm it in 24 hours, your submission\r\n will be removed automatically.</p>\r\n<p>If you have not submited an entry to our web site, please <a href=\"{$site_url}\">contact us here</a>.</p>'),
('en',	'l_mail_add_subject',	'Your recent submission: %s'),
('en',	'l_mail_add_subject_adm',	'New submission: %s'),
('en',	'msg.invalid_key',	'<h1>Invalid Key!</h1>\r\n<p>Please make sure the key is valid! If you have lost the key, please <a href=\"{$site_url}/add.php?cmd=lost\">restore the key here</a>.</p>'),
('en',	'msg.item_status_not_t',	'<h1>Listing Was Confirmed</h1>\r\n<p>The listing was confirmed before. Please wait until it is accepted by us.</p>'),
('en',	'msg.item_status_set_e',	'<h1>Thank You</h1>\r\n<p>Thank you for your confirmation. Your listing has now been sent to the administrator for approval. We will inform you as soon as possible.</p>'),
('en',	'msg.add_thanks',	'<h1>Thank You</h1>\r\n<p>Thank you for your submission. Your listing has now been sent to the administrator for approval. We will inform you as soon as possible.</p>'),
('en',	'mail.item_status_p',	'<h1>Congratulation!</h1>\r\n<p>Your recent submission for <a href=\"{$site_url}\">{$site_name}</a> <b>has been approved!</b></p>\r\n<p><b>Directory: {$dir_title}</b><br />\r\nTitle: {$item_title}<br />\r\n{$optional_fields}\r\nDetails: {$item_details}</p>\r\n\r\n<p><b>Other Information</b><br />\r\n{$cf_email}</p>\r\n\r\n<p>Please keep this email for future reference.</p>\r\n<p>If you have not submited an entry to our web site, please <a href=\"{$site_url}/contact.php\">contact us here</a>.</p>'),
('en',	'mail.item_status_e',	'<h1>Hi!</h1>\r\n<p>Your recent submission for <a href=\"{$site_url}\">{$site_name}</a> <b>has been set to pending!</b></p>\r\n<p><b>Directory: {$dir_title}</b><br />\r\nTitle: {$item_title}<br />\r\n{$optional_fields}\r\nDetails: {$item_details}</p>\r\n\r\n<p><b>Other Information</b><br />\r\n{$cf_email}</p>\r\n\r\n<p>If you think this is a mistake, please <a href=\"$config[site_url]/contact.php\">contact us here</a>.</a>\r\n<p>To modify your listing, please use <a href=\"{$site_url}/add.php?cmd=edit&amp;item_id={$item_id}&amp;secret_key={$owner_passwd}\">this link</a>.\r\nIf you are already a member, you can always edit it from your member area.</p>\r\n<p>If you have not submited an entry to our web site, please<a href=\"{$site_url}/contact.php\">contact us here</a>.</p>'),
('en',	'l_edit_item',	'Edit Listing'),
('en',	'mail.change_e',	'<p>There is a <b>change request</b> for <a href=\"{$site_url}\">{$site_name}</a> as follow:</p>\r\n<p><b>Directory: {$dir_title}</b><br />\r\nTitle: {$item_title}<br />\r\n{$optional_fields}\r\nDetails: {$item_details}</p>\r\n\r\n<p><b>User Information</b><br />\r\nUser ID: {$owner_id}<br />\r\nEmail: {$owner_email}</p>\r\n\r\n<p><b>Custom Fields</b><br />\r\n{$cf_email}</p>\r\n\r\n<p>You can manage this request &amp; its original values from ACP: <a href=\"{$site_url}/admin/listing.php?cmd=edit&item_id={$item_id}\">{$site_url}/admin/listing.php?cmd=edit&item_id={$item_id}</a></p>'),
('en',	'msg.change_ok',	'<h1>Changes Sent</h1>\r\n<p>We have received your change request. We will process your request as soon as possible. Thank you!</p>'),
('en',	'l_mail_change_subject_adm',	'Change Request: %s'),
('en',	'msg.no_change',	'<h1>No Changes</h1>\r\n<p>No changes detected! If you feel this is a mistake, please contact us.</p>'),
('en',	'mail.item_status_x',	'<h1>Hi!</h1>\r\n<p>Your recent submission for <a href=\"{$site_url}\">{$site_name}</a> has been <b>rejected!</b></p>\r\n<p><b>Directory: {$dir_title}</b><br />\r\nTitle: {$item_title}<br />\r\n{$optional_fields}\r\nDetails: {$item_details}</p>\r\n\r\n<p><b>Other Information</b><br />\r\n{$cf_email}</p>\r\n\r\n<p>If you think this is a mistake, please <a href=\"$config[site_url]/contact.php\">contact us here</a>.</a>\r\n<p>If you have not submited an entry to our web site, please <a href=\"{$site_url}/contact.php\">contact us here</a>.</p>'),
('en',	'msg.item_not_found',	'<h1>Not Found</h1><p>The requested listing was not found. It probably needs to be approved, first.</p>'),
('en',	'msg.edit_item_not_found',	'<h1>Not Found</h1><p>The requested listing not found, invalid password, or not yours.</p>'),
('en',	'mail.lost_edit',	'<h1>Hi!</h1>\r\n<p>The following is your password for your submission for <a href=\"{$site_url}\">{$site_name}</a>:</p>\r\n<p><b>Directory: {$dir_title}</b><br />\r\nTitle: {$item_title}<br />\r\nItem ID: {$item_id}<br />\r\nPassword: {$owner_passwd}</p>\r\n\r\n<p>If you need to modify your listing, simply go to: <a href=\"{$site_url}/add.php?cmd=edit_guest\">{$site_url}/add.php?cmd=edit_guest</a>, and enter above information.</p>\r\n\r\n<p>If you have not asked to reset the password, rest assured that your listing is still safe, and simply use the above information.</p>\r\n<p>If you have not submited an entry to our web site, please <a href=\"{$site_url}/contact.php\">contact us here</a>.</p>'),
('en',	'l_mail_lost_edit_subject',	'Password For %s'),
('en',	'l_select',	'Select'),
('en',	'l_can_not_upgrade',	'Cannot upgrade the selected listing now. It needs to be approved first.'),
('en',	'l_method',	'Method'),
('en',	'l_fee',	'Fee'),
('en',	'mail.checkout_admin',	'<p>You have just got a new order!</p>\r\n<h3>Order Information</h3>\r\n<p><b>Order ID:</b> {$order_id}<br />\r\n<b>Order date:</b> {$today}</p>\r\n\r\n<h3>Upgrade Request for {$item_title}</h3>\r\n<p>Upgrade request to {$upgrade_to} until {$valid_until}<br />\r\nTotal: {$period} month(s) &times; {$price} = {$total}</p>\r\n\r\n<h3>Payment Information</h3>\r\n<p><b>Selected method of payment:</b> {$payment_method}<br /><b>Payment status:</b> {$payment_status}</p>\r\n<p>If this order paid using PayPal IPN, be sure to recheck the PayPal log manually from your ACP.</p><p>You can manage this transaction at: <a href=\"{$adm_check_url}\">{$adm_check_url}</a></p>'),
('en',	'mail.checkout',	'<h3 align=\"right\">Order Confirmation</h3>\r\n<p>Hi,</p><p>Thank you for ordering at {$site_name}, here are the details of your order.</p>\r\n<table border=\"0\" cellpadding=\"3\" cellspacing=\"3\" width=\"100%\">\r\n <tr><th width=\"40%\">Username</th><td width=\"60%\">{$owner_id}</td></tr>\r\n  <tr><th width=\"40%\">Order ID</th><td width=\"60%\">{$order_id} on {$today}</td></tr>\r\n  <tr><th width=\"40%\">Payment Method</th><td width=\"60%\">{$payment_method}</td></tr>\r\n</table>\r\n\r\n<table border=\"1\" cellpadding=\"3\" style=\"border-collapse: collapse; border-color:#999;border:solid 1px #999\" width=\"100%\">\r\n  <tr>\r\n    <th width=\"50%\" class=\"items\">Description</th>\r\n    <th width=\"10%\" class=\"items\">Qty</th>\r\n    <th width=\"20%\" class=\"items\">Unit Price</th>\r\n   <th width=\"20%\" class=\"items\">Total</th></tr>\r\n <tr>\r\n    <td><a href=\"{$site_url}/{$url}\">{$item_title}</a><br />Upgrade request to {$upgrade_to} until {$valid_until} - {$period} month(s).</td>\r\n    <td align=\"center\">{$period}</td>\r\n   <td align=\"right\">{$price}</td>\r\n   <td width=\"29%\" align=\"right\">{$total}</td>\r\n </tr>\r\n</table>\r\n\r\n<!-- BEGINIF $howtopay -->\r\n<p>You have selected {$payment_method} for payment method. Please refer to the following information on how to pay for your orders.</p>\r\n{$howtopay}\r\n<!-- ENDIF -->\r\n\r\n<p>Thank you for your patronage. This order confirmation has been automatically generated by our order tracking system.</p>\r\n<p>Should you have any questions about your order, please visit the following url for updated order information: <a href=\"{$trx_check_url}\">{$trx_check_url}</a></p>\r\n<p>Yours sincerely,<br />\r\nCustomer Service Department<br /><b>{$site_name}</b><br />\r\n<a href=\"{$site_url}\">{$site_url}</a></p>'),
('en',	'l_mail_expired_subject',	'Your listing will expire: %s'),
('en',	'l_pay_redir',	'You will be redirected to the payment portal'),
('en',	'l_pay_redir_3s',	'Click here, if you are not redirected in 3 seconds!'),
('en',	'mail.soon_expired',	'<h1>Hi,</h1>\r\n<p>We notice that one of your listings is about to expire its premium or sponsored status.</p>\r\n\r\n<p><b><a href=\"{$site_url}/{$url}\">{$item_title}</a></b><br />\r\nCategory: {$dir_name}{$cat_name}<br />\r\nCurrent Class: {$item_class}<br />\r\nExpiry Date: {$item_valid_date}</p>\r\n\r\n<p>To maintain your premium or sponsored status, simply edit your listing and choose Upgrade.</p>\r\n<p>If you decide not to upgrade it, your listing will be reverted back to Standard listing, and you can upgrade it anytime in the future.</p>\r\n<p>Yours sincerely,<br />\r\nCustomer Service Department<br /><b>{$l_site_name}</b><br />\r\n<a href=\"{$site_url}\">{$site_url}</a></p>'),
('en',	'l_mail_order_admin_subject',	'%1$s - New Order - ID: %2$s'),
('en',	'l_mail_order_subject',	'%1$s - Your Order  - #%2$s'),
('en',	'l_how_to_pay',	'How To Pay'),
('en',	'mail.item_orphaned',	'<p>System has detected an orphaned item for <a href=\"{$site_url}\">{$site_name}</a> as follow:</p>\r\n<p><b>Directory: {$dir_title}</b><br />\r\nTitle: {$item_title}<br />\r\nDetails: {$item_details}</p>\r\n\r\n<p>Items may be accidentally orphaned if you removed a category.</p>\r\n\r\n<p>You can manage this submission from ACP: <a href=\"{$site_url}/admin/listing.php?cmd=edit&item_id={$item_id}\">{$site_url}/admin/listing.php?cmd=edit&item_id={$item_id}</a></p>'),
('en',	'msg.add_temp',	'<h1>Confirmation Needed!</h1>\r\n<p>Thank you for your submission, but first you need to confirm your submission before the administrator can review your listing. Please follow the information in the email we have sent to you.</p>'),
('en',	'msg.update_ok',	'<h1>Success!</h1>\r\n<p>Your change request has been sent to the administrator for review. We will inform you as soon as possible. Thank you!</p>'),
('en',	'msg.cat_error',	'<h1>Category Not Found</h1>\r\n<p>Category may have been removed. Please contact us for more information.</p>'),
('en',	'l_remove_favorite',	'Remove From Favorite'),
('en',	'l_featured_listing',	'Featured Listings'),
('en',	'l_newest_listing',	'Newest Listings'),
('en',	'l_browse',	'Browse'),
('en',	'l_welcome',	'Welcome'),
('en',	'l_my_listing',	'My Listing'),
('en',	'l_my_listing_why',	'Manage, edit & upgrade your listings.'),
('en',	'l_my_order',	'My Orders'),
('en',	'l_my_order_why',	'Manage your past & current transactions.'),
('en',	'l_my_favorite',	'My Favorites'),
('en',	'l_my_favorite_why',	'Manage your favorite listings.'),
('en',	'l_active_listing',	'Active Listings'),
('en',	'l_pending_listing',	'Pending Listings'),
('en',	'l_order_id',	'Order ID'),
('en',	'l_requested_class',	'Requested Class'),
('en',	'l_status',	'Status'),
('en',	'l_current_class',	'Current Class'),
('en',	'l_period',	'Period'),
('en',	'l_monthly_fee',	'Monthly Fee'),
('en',	'l_total',	'Total'),
('en',	'l_payment_method',	'Payment Method'),
('en',	'l_payment_status',	'Payment Status'),
('en',	'l_order_date',	'Order Date'),
('en',	'l_sitemap',	'Sitemap'),
('en',	'l_add_listing',	'Add Listing'),
('en',	'l_edit_listing',	'Edit Listing'),
('en',	'l_upgrade_listing',	'Upgrade Listing'),
('en',	'l_listing',	'Listings'),
('en',	'l_select_dir',	'Please select a directory:'),
('en',	'l_edit_guest_why',	'Use this form if you want to edit your listings submitted as a guest. If you are a member, please login to see all your listings in one place.'),
('en',	'l_item_id',	'Item ID'),
('en',	'l_edit_lost_why',	'Use this to reset or edit your password. A new password will be sent to your email address. If you are a member, please login to see all your listings in one place.'),
('en',	'l_upgrade_why',	'<p>Promote your listing, to make it stand out from the rest, by upgrading to the premium or sponsored level. A premium listing turns your entry green, so that it sticks out on the page. A sponsored listing additionally puts your listing at the top of the page with a red \"Sponsored\" band in the corner</p> <ul> <li>Premium entries stand out with a green background.</li> <li>Sponsored listings always appears first.</li> <li>Stand out for more exposure with different backgrounds in search result.</li> <li>More detailed information.</li> <li>Affordable rates.</li> <li>Accept PayPal for instant approval.</li> </ul>'),
('en',	'l_main_category',	'Main Category'),
('en',	'l_upgrade_now',	'Upgrade Now'),
('en',	'l_target_url',	'Target URL'),
('en',	'l_backlink_url',	'Backlink URL'),
('en',	'l_logo',	'Logo'),
('en',	'l_summary',	'Summary'),
('en',	'l_more_details',	'More Details'),
('en',	'l_captcha',	'Captcha'),
('en',	'l_month',	'Month'),
('en',	'l_months',	'Months'),
('en',	'l_next',	'Next'),
('en',	'l_i_have_confirm',	'I confirm the above information is correct.'),
('en',	'l_valid_until',	'Valid Until'),
('en',	'l_clear',	'Clear'),
('en',	'l_remove',	'Remove'),
('en',	'l_remove_confirm',	'Are you sure to remove this item? This can not be undone!'),
('en',	'l_user_level_1',	'Bronze'),
('en',	'l_user_level_2',	'Silver'),
('en',	'l_user_level_3',	'Gold'),
('en',	'l_user_level_4',	'Platinum'),
('en',	'l_user_level_5',	'Diamond'),
('en',	'l_admin_level_1',	'Staffs'),
('en',	'l_admin_level_2',	'Supervisors'),
('en',	'l_admin_level_3',	'Managers'),
('en',	'l_admin_level_4',	'Administrators'),
('en',	'l_admin_level_5',	'Owners'),
('en',	'l_url_mask',	'URL Masking'),
('en',	'l_filter_result',	'Filter Results'),
('en',	'l_listing_info',	'Listing Information'),
('en',	'l_warning',	'Warning!'),
('en',	'l_upgrade_warning',	'You are about to change current listing class from <b>{$from}</b> to <b>{$to}</b>.<br />This will remove the remaining {$from} period!'),
('en',	'l_video_help',	'Paste a video URL from Youtube or Vimeo');

DROP TABLE IF EXISTS `__PREFIX__listing`;
CREATE TABLE `__PREFIX__listing` (
  `idx` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `dir_id` int(10) unsigned NOT NULL,
  `owner_id` varchar(255) NOT NULL,
  `owner_email` varchar(255) NOT NULL,
  `owner_passwd` varchar(255) NOT NULL,
  `category_1` int(10) unsigned NOT NULL,
  `category_2` int(10) unsigned NOT NULL,
  `category_3` int(10) unsigned NOT NULL,
  `category_4` int(10) unsigned NOT NULL,
  `category_5` int(10) unsigned NOT NULL,
  `category_6` int(10) unsigned NOT NULL,
  `item_permalink` varchar(255) NOT NULL,
  `item_title` varchar(255) NOT NULL,
  `item_url` varchar(255) NOT NULL,
  `item_url_mask` varchar(255) NOT NULL,
  `item_summary` varchar(255) NOT NULL,
  `item_details` text NOT NULL,
  `item_status` enum('P','E','T') NOT NULL DEFAULT 'E',
  `item_sort_point` int(11) NOT NULL,
  `item_class` enum('R','P','S') NOT NULL DEFAULT 'R',
  `item_date` date NOT NULL,
  `item_update` date NOT NULL,
  `item_valid_date` date NOT NULL,
  `item_backlink_url` varchar(255) NOT NULL,
  `item_backlink_ok` char(1) NOT NULL,
  `item_visibility` enum('A','M','H') NOT NULL DEFAULT 'A',
  `item_keyword` varchar(255) NOT NULL,
  `item_rating` decimal(3,2) NOT NULL,
  `item_votes` int(10) unsigned NOT NULL,
  `see_also` varchar(255) NOT NULL,
  `stat_hits` int(10) unsigned NOT NULL,
  `menu_idx` int(10) unsigned NOT NULL,
  `original_idx` int(10) unsigned NOT NULL,
  `expired_email` enum('0','1') NOT NULL DEFAULT '0',
  `orphaned` enum('0','1') NOT NULL DEFAULT '0',
  `last_calculated` date NOT NULL,
  `smart_search` text NOT NULL,
  PRIMARY KEY (`idx`),
  KEY `dir_id` (`dir_id`),
  KEY `owner_id` (`owner_id`),
  KEY `owner_email` (`owner_email`),
  KEY `category_1` (`category_1`),
  KEY `category_2` (`category_2`),
  KEY `category_3` (`category_3`),
  KEY `category_4` (`category_4`),
  KEY `category_5` (`category_5`),
  KEY `category_6` (`category_6`),
  KEY `item_sort_point` (`item_sort_point`),
  KEY `item_class` (`item_class`),
  KEY `item_visibility` (`item_visibility`),
  KEY `item_url` (`item_url`),
  KEY `item_rating` (`item_rating`),
  KEY `item_status` (`item_status`),
  KEY `item_date` (`item_date`),
  KEY `menu_idx` (`menu_idx`),
  KEY `original_idx` (`original_idx`),
  KEY `expired_email` (`expired_email`),
  KEY `last_calculated` (`last_calculated`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `__PREFIX__listing` (`idx`, `dir_id`, `owner_id`, `owner_email`, `owner_passwd`, `category_1`, `category_2`, `category_3`, `category_4`, `category_5`, `category_6`, `item_permalink`, `item_title`, `item_url`, `item_url_mask`, `item_summary`, `item_details`, `item_status`, `item_sort_point`, `item_class`, `item_date`, `item_update`, `item_valid_date`, `item_backlink_url`, `item_backlink_ok`, `item_visibility`, `item_keyword`, `item_rating`, `item_votes`, `see_also`, `stat_hits`, `menu_idx`, `original_idx`, `expired_email`, `orphaned`, `last_calculated`, `smart_search`) VALUES
(1, 1,  'admin',  'contact@c97.net',  '', 1,  0,  0,  0,  0,  0,  'example-listing.php',  'Example Listing',  '', '', '', 'This is just a sample listing. You can remove it from ACP.\r\n\r\nLorem ipsum dolor sit amet, consectetur adipiscing elit. In non urna erat. Aliquam placerat imperdiet sem sit amet consequat. Sed convallis augue vitae nisi efficitur ullamcorper. Etiam eu imperdiet magna. Proin quis aliquam elit. Aenean facilisis viverra accumsan. Donec porttitor euismod nibh at dapibus.', 'P',  0,  'R',  '2016-09-25', '0000-00-00', '2016-09-25', '', '0',  'A',  '', 0.00, 0,  '', 3,  0,  0,  '0',  '0',  '2017-09-03', 'example listing this is just a sample you can remove it from acp lorem ipsum dolor sit amet consectetur adipiscing elit in non urna erat aliquam placerat imperdiet sem consequat sed convallis augue vitae nisi efficitur ullamcorper etiam eu magna proin quis aenean facilisis viverra accumsan donec porttitor euismod nibh at dapibus ');

DROP TABLE IF EXISTS `__PREFIX__listing_cat`;
CREATE TABLE `__PREFIX__listing_cat` (
  `parent_id` int(10) unsigned NOT NULL DEFAULT '0',
  `idx` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `dir_id` int(10) unsigned NOT NULL,
  `cat_name` varchar(100) NOT NULL DEFAULT '',
  `cat_details` text NOT NULL,
  `cat_image` varchar(255) NOT NULL DEFAULT '',
  `cat_keywords` varchar(255) NOT NULL,
  `cat_featured` varchar(255) NOT NULL DEFAULT '0',
  `cat_page` varchar(10) NOT NULL,
  `cat_num_link` int(10) unsigned NOT NULL,
  `menu_idx` int(10) unsigned NOT NULL,
  `menu_item_id` int(10) unsigned NOT NULL,
  `permalink` varchar(255) NOT NULL,
  `is_removed` enum('0','1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`idx`),
  KEY `menu_idx` (`menu_idx`),
  KEY `menu_item_id` (`menu_item_id`),
  KEY `dir_id` (`dir_id`),
  KEY `parent_id` (`parent_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `__PREFIX__listing_cat` (`parent_id`, `idx`, `dir_id`, `cat_name`, `cat_details`, `cat_image`, `cat_keywords`, `cat_featured`, `cat_page`, `cat_num_link`, `menu_idx`, `menu_item_id`, `permalink`, `is_removed`) VALUES
(0, 1,  1,  'Default Category', '<p>This is a dummy category, you can remove it from ACP.</p>', '', '', '', '', 1,  6,  14, 'category/default-category.php',  '');

DROP TABLE IF EXISTS `__PREFIX__listing_cf_define`;
CREATE TABLE `__PREFIX__listing_cf_define` (
  `idx` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `dir_id` int(10) unsigned NOT NULL,
  `cf_title` varchar(255) NOT NULL,
  `cf_type` varchar(10) NOT NULL,
  `cf_option` text NOT NULL,
  `cf_help` varchar(255) NOT NULL,
  `is_searchable` enum('0','1') NOT NULL DEFAULT '0',
  `is_required` enum('0','1') NOT NULL DEFAULT '0',
  `is_list` enum('0','1') NOT NULL DEFAULT '0',
  `avail_to` varchar(20) NOT NULL,
  `menu_idx` int(10) unsigned NOT NULL,
  `menu_item_id` int(10) unsigned NOT NULL,
  `is_removed` enum('0','1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`idx`),
  KEY `cf_dir_id` (`dir_id`),
  KEY `menu_idx` (`menu_idx`),
  KEY `menu_item_id` (`menu_item_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `__PREFIX__listing_cf_value`;
CREATE TABLE `__PREFIX__listing_cf_value` (
  `idx` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `item_id` int(10) unsigned NOT NULL,
  PRIMARY KEY (`idx`),
  KEY `item_id` (`item_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `__PREFIX__listing_cf_value` (`idx`, `item_id`) VALUES
(1, 1);

DROP TABLE IF EXISTS `__PREFIX__listing_dir`;
CREATE TABLE `__PREFIX__listing_dir` (
  `idx` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `dir_short` char(3) NOT NULL,
  `dir_title` varchar(255) NOT NULL,
  `dir_permalink` varchar(255) NOT NULL,
  `dir_image` varchar(255) NOT NULL,
  `dir_body` text NOT NULL,
  `dir_backlink` enum('0','1') NOT NULL DEFAULT '0',
  `dir_summary` enum('0','1') NOT NULL DEFAULT '0',
  `dir_url` enum('0','1') NOT NULL DEFAULT '0',
  `dir_url_mask` enum('0','1') NOT NULL DEFAULT '0',
  `dir_multi_cat` tinyint(3) unsigned NOT NULL,
  `dir_no_detail` enum('0','1') NOT NULL DEFAULT '0',
  `dir_per_page` tinyint(3) unsigned NOT NULL,
  `dir_logo` enum('0','1') NOT NULL DEFAULT '1',
  `dir_logo_size` int(10) unsigned NOT NULL,
  `dir_comment` enum('0','1') NOT NULL DEFAULT '1',
  `dir_default_sort` char(2) NOT NULL,
  `dir_default_view` enum('grid','list') NOT NULL DEFAULT 'grid',
  `dir_pre_allow` enum('0','1') NOT NULL DEFAULT '1',
  `dir_spo_allow` enum('0','1') NOT NULL DEFAULT '1',
  `dir_pre_fee` decimal(10,2) unsigned NOT NULL,
  `dir_spo_fee` decimal(10,2) unsigned NOT NULL,
  `dir_cat_menu_id` int(10) unsigned NOT NULL,
  `dir_cf_menu_id` int(10) unsigned NOT NULL,
  `dir_featured` varchar(255) NOT NULL,
  `dir_default` enum('0','1') NOT NULL DEFAULT '0',
  `menu_item_id` int(10) unsigned NOT NULL,
  `is_removed` enum('0','1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`idx`),
  KEY `dir_id` (`dir_short`),
  KEY `dir_menu_id` (`dir_cat_menu_id`),
  KEY `menu_item_id` (`menu_item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `__PREFIX__listing_dir` (`idx`, `dir_short`, `dir_title`, `dir_permalink`, `dir_image`, `dir_body`, `dir_backlink`, `dir_summary`, `dir_url`, `dir_multi_cat`, `dir_per_page`, `dir_logo`, `dir_logo_size`, `dir_comment`, `dir_default_sort`, `dir_default_view`, `dir_pre_allow`, `dir_spo_allow`, `dir_pre_fee`, `dir_spo_fee`, `dir_cat_menu_id`, `dir_cf_menu_id`, `dir_featured`, `dir_default`, `menu_item_id`, `is_removed`) VALUES
(1, 'gen',  'General Directory',  'general-directory.php',  '', '<p>This is a dummy directory, you can remove it from ACP. Your web site must have at least one directory!</p>',  '0',  '0',  '0',  6,  24, '1',  0,  '1',  'xd', 'grid', '0',  '1',  0.00, 0.00, 6,  7,  '', '1',  13, '');

DROP TABLE IF EXISTS `__PREFIX__mailog`;
CREATE TABLE `__PREFIX__mailog` (
  `log_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `log_address` varchar(255) NOT NULL DEFAULT '',
  `log_subject` varchar(255) NOT NULL DEFAULT '',
  `log_body` text NOT NULL,
  `log_time` int(10) unsigned NOT NULL DEFAULT '0',
  `log_html` char(1) NOT NULL DEFAULT '',
  PRIMARY KEY (`log_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `__PREFIX__menu_item`;
CREATE TABLE `__PREFIX__menu_item` (
  `idx` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `menu_id` int(10) unsigned NOT NULL,
  `menu_parent` int(10) unsigned NOT NULL,
  `menu_item` varchar(255) NOT NULL,
  `menu_url` varchar(255) NOT NULL,
  `menu_permalink` varchar(255) NOT NULL,
  `menu_order` int(10) unsigned NOT NULL,
  `ref_idx` int(10) unsigned NOT NULL,
  PRIMARY KEY (`idx`),
  KEY `menu_id` (`menu_id`),
  KEY `ref_idx` (`ref_idx`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `__PREFIX__menu_item` (`idx`, `menu_id`, `menu_parent`, `menu_item`, `menu_url`, `menu_permalink`, `menu_order`, `ref_idx`) VALUES
(1, 2,  0,  'Contact Us', '__SITE__/contact.php', '', 110,  0),
(2, 2,  0,  'Site Map', '__SITE__/sitemap.php', '', 100,  0),
(4, 2,  0,  'Tell a Friend',  '__SITE__/tell.php',  '', 120,  0),
(5, 3,  0,  'Privacy Policy', '2',  '', 100,  0),
(6, 3,  0,  'Terms &amp; Conditions', '7',  '', 110,  0),
(7, 3,  0,  'Powered by qEngine', '8',  '', 120,  0),
(8, 3,  0,  'FAQ&#039;s', '3',  '', 130,  0),
(9, 3,  0,  'About Us', '4',  '', 140,  0),
(10,  1,  0,  'Home', '__SITE__', '', 100,  0),
(11,  1,  0,  'Add Listing',  '__SITE__/add.php', '', 110,  0),
(12,  1,  0,  '#',  '[[sm:dir_menu]]',  '', 120,  0),
(13,  5,  0,  'General Directory',  '__SITE__/index.php?dir_id=1',  '__SITE__/general-directory.php', 100,  1),
(14,  6,  0,  'Default Category', '__SITE__/listing_search.php?cmd=list&amp;cat_id=1',  '__SITE__/category/default-category.php', 100,  1),
(16,  2,  0,  'Backlinking',  '14', '', 100,  0);

DROP TABLE IF EXISTS `__PREFIX__menu_set`;
CREATE TABLE `__PREFIX__menu_set` (
  `idx` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `menu_id` varchar(255) NOT NULL,
  `menu_title` varchar(255) NOT NULL,
  `menu_preset` varchar(255) NOT NULL,
  `menu_class` varchar(255) NOT NULL,
  `menu_notes` text NOT NULL,
  `menu_cache` text NOT NULL,
  `menu_locked` enum('0','1') NOT NULL DEFAULT '0',
  `ref_idx` int(10) unsigned NOT NULL,
  PRIMARY KEY (`idx`),
  KEY `ref_idx` (`ref_idx`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `__PREFIX__menu_set` (`idx`, `menu_id`, `menu_title`, `menu_preset`, `menu_class`, `menu_notes`, `menu_cache`, `menu_locked`, `ref_idx`) VALUES
(1, 'main_menu',  'Main Menu',  'bsnav',  '', 'Main menu, usually located at the top of the page.', '<ul id=\"qmenu_main_menu\" class=\"nav navbar-nav\">\n <li><a href=\"__SITE__\">Home</a></li>\n  <li><a href=\"__SITE__/add.php\">Add Listing</a></li>\n <li><a href=\"[[sm:dir_menu]]\">#</a></li>\n</ul>\n', '0',  0),
(2, 'footer_menu',  'Footer Menu',  'list_1', '', 'Footer menu, usually located at the end of the page.', '<ul id=\"qmenu_footer_menu\" class=\"list_1\">\n <li><a href=\"__SITE__/sitemap.php\">Site Map</a></li>\n  <li><a href=\"__SITE__/page.php?pid=14\">Backlinking</a></li>\n <li><a href=\"__SITE__/contact.php\">Contact Us</a></li>\n  <li><a href=\"__SITE__/tell.php\">Tell a Friend</a></li>\n</ul>\n', '0',  0),
(3, 'page_menu',  'Page Menu',  'list_1', '', 'Menu linking to some important, but not that important pages.',  '<ul id=\"qmenu_page_menu\" class=\"list_1\">\n <li><a href=\"__SITE__/page.php?pid=2\">Privacy Policy</a></li>\n <li><a href=\"__SITE__/page.php?pid=7\">Terms & Conditions</a></li>\n <li><a href=\"__SITE__/page.php?pid=8\">Powered by qEngine</a></li>\n <li><a href=\"__SITE__/page.php?pid=3\">FAQ\'s</a></li>\n <li><a href=\"__SITE__/page.php?pid=4\">About Us</a></li>\n</ul>\n',  '0',  0),
(5, 'dir_menu', 'Multiple Directories Menu',  'sf-menu',  '', 'Multiple directories menu. Do NOT remove!',  '<ul id=\"qmenu_dir_menu\" class=\"sf-menu\">\n <li><a href=\"__SITE__/index.php?dir_id=1\">General Directory</a></li>\n</ul>\n', '1',  0),
(6, 'dir_cat_gen',  'Categories for General Directory', 'dir_cat.1',  '', 'Container for category menu of General Directory. Do NOT remove!', '<ul id=\"qmenu_dir_cat_gen\" class=\"dir_cat.1\">\n  <li><a href=\"__SITE__/listing_search.php?cmd=list&amp;cat_id=1\">Default Category</a></li>\n</ul>\n',  '1',  0),
(7, 'dir_cf_gen', 'Custom field for General Directory', 'dir_cf.1', '', 'Container for custom field menu of General Directory. Do NOT remove!', '', '1',  0);

DROP TABLE IF EXISTS `__PREFIX__module`;
CREATE TABLE `__PREFIX__module` (
  `mod_id` varchar(255) NOT NULL DEFAULT '',
  `mod_type` enum('general','shipping','payment') NOT NULL DEFAULT 'general',
  `mod_name` varchar(255) NOT NULL DEFAULT '',
  `mod_desc` text NOT NULL,
  `mod_version` varchar(10) NOT NULL DEFAULT '',
  `mod_css` varchar(255) NOT NULL,
  `mod_js` varchar(255) NOT NULL,
  `mod_enabled` char(1) NOT NULL DEFAULT '',
  PRIMARY KEY (`mod_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `__PREFIX__module` (`mod_id`, `mod_type`, `mod_name`, `mod_desc`, `mod_version`, `mod_css`, `mod_js`, `mod_enabled`) VALUES
('box', 'general',  'Box',  'A simple module to display static html for your page, without editing .tpl files, best used with qE 4.x\'s Module Manager.', '1.0.0',  '', '', '1'),
('ke_core', 'general',  'Kemana 2 Core Module', 'This is a multipurpose module for Kemana 2. This module contains support for item listings and custom fields.',  '1.0.0',  'module_ke_core.css', '', '1'),
('page_gallery',  'general',  'Page Gallery', 'Display selected pages or categories or groups anywhere!', '2.0.0',  '', '', '1'),
('pay_bank',  'payment',  'Bank Wire Transfer', 'A payment gateway for Bank Wire Transfer.',  '1.0.0',  '', '', '1'),
('pay_cheque',  'payment',  'Cheque', 'A payment gateway for By Cheque.', '1.0.0',  '', '', '1'),
('pay_paypal',  'payment',  'PayPal', 'A payment gateway for PayPal (IPN). (Also contains information for developers)', '1.0.0',  '', '', '1'),
('qbanner', 'general',  'qBanner',  'Use this module to upload & display banners.', '1.0.0',  '', '', '1'),
('qcomment',  'general',  'qComment', 'Add user comments & user ratings to your site and your modules, easily!',  '3.0.0',  '', '', '1'),
('qmenu', 'general',  'qMenu',  'Use qMenu module to display your designed menu easily!', '1.0.0',  '', '', '1'),
('qstats',  'general',  'Simple Stats', 'This module replaces qEngine\'s old simple statistics of visitors\' hits & visits.', '1.0.0',  '', '', '1'),
('slideshow', 'general',  'Slideshow',  'This module to replace qEngine\'s old featured contents.', '1.0.0',  'slideshow.css',  '', '1'),
('ztopwatch', 'general',  'Ztopwatch',  'This module replace the old stopwatch in qEngine 1', '1.0.0',  '', '', '1');

DROP TABLE IF EXISTS `__PREFIX__module_pos`;
CREATE TABLE `__PREFIX__module_pos` (
  `idx` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `mod_id` varchar(255) NOT NULL,
  `mod_title` varchar(255) NOT NULL,
  `mod_config` text NOT NULL,
  `mod_pos` char(2) NOT NULL,
  PRIMARY KEY (`idx`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `__PREFIX__module_pos` (`idx`, `mod_id`, `mod_title`, `mod_config`, `mod_pos`) VALUES
(1, 'box',  'Add Anything!',  '&lt;p&gt;You can easily adds any HTML or JavaScript tags by editing this module, or create a new box, by using Box Module in ACP &gt; Modules &gt; Layout.&lt;/p&gt;\r\n\r\n&lt;p&gt;Add Google AdSense, Facebook Feeds, Twitter Updates, by editing this module.&lt;/p&gt;',  'R1'),
(2, 'box',  'Info Box', '&lt;p&gt;Manage this module from ACP. Display up to 40 modules easily!&lt;/p&gt;\r\n\r\n&lt;p&gt;You can also remove this information from Module Management.&lt;/p&gt;\r\n\r\n&lt;p&gt;In default skin, this module appears on the right.&lt;/p&gt;', 'L2'),
(3, 'qbanner',  'Banner', '', 'L1'),
(4, 'qmenu',  'Tools',  'menu=footer_menu', 'B1'),
(5, 'qmenu',  'Pages',  'menu=page_menu', 'B1'),
(6, 'qmenu',  'qMenu',  'menu=main_menu', 'T2'),
(9, 'qstats', 'Simple Stats', '', 'R2');

DROP TABLE IF EXISTS `__PREFIX__notification`;
CREATE TABLE `__PREFIX__notification` (
  `idx` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `notify_time` int(10) unsigned NOT NULL,
  `notify_from` varchar(255) NOT NULL,
  `notify_to` varchar(255) NOT NULL,
  `notify_admin` enum('0','1') NOT NULL DEFAULT '0',
  `notify_subject` varchar(255) NOT NULL,
  `notify_url` varchar(255) NOT NULL,
  `notify_read` enum('0','1') NOT NULL DEFAULT '0',
  `notify_popup` enum('0','1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`idx`),
  KEY `notify_to` (`notify_to`),
  KEY `notify_admin` (`notify_admin`),
  KEY `notify_popup` (`notify_popup`),
  KEY `notify_from` (`notify_from`),
  KEY `notify_read` (`notify_read`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `__PREFIX__order`;
CREATE TABLE `__PREFIX__order` (
  `idx` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `order_id` varchar(16) NOT NULL DEFAULT '',
  `user_id` varchar(80) NOT NULL DEFAULT '',
  `user_email` varchar(255) NOT NULL,
  `item_id` int(10) unsigned NOT NULL,
  `target_class` enum('P','S') NOT NULL,
  `item_period` tinyint(3) unsigned NOT NULL,
  `order_date` date NOT NULL DEFAULT '0000-00-00',
  `order_price` decimal(10,2) NOT NULL DEFAULT '0.00',
  `order_total` decimal(10,2) NOT NULL DEFAULT '0.00',
  `order_tax` decimal(10,2) NOT NULL DEFAULT '0.00',
  `order_payment` varchar(80) NOT NULL DEFAULT '',
  `order_paystat` char(1) NOT NULL DEFAULT 'E',
  `order_status` char(1) NOT NULL DEFAULT 'E',
  `order_completed` date NOT NULL,
  `order_cancelled` date NOT NULL,
  PRIMARY KEY (`order_id`),
  UNIQUE KEY `idx` (`idx`),
  KEY `order_date` (`order_date`),
  KEY `user_id` (`user_id`),
  KEY `item_id` (`item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 PACK_KEYS=0 COMMENT='Order summary';


DROP TABLE IF EXISTS `__PREFIX__page`;
CREATE TABLE `__PREFIX__page` (
  `group_id` varchar(5) NOT NULL,
  `cat_id` int(10) unsigned NOT NULL,
  `page_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `permalink` varchar(255) NOT NULL,
  `page_image` varchar(255) NOT NULL DEFAULT '',
  `page_date` date NOT NULL DEFAULT '0000-00-00',
  `page_time` time NOT NULL,
  `page_unix` int(10) unsigned NOT NULL,
  `page_title` varchar(255) NOT NULL DEFAULT '',
  `page_keyword` varchar(255) NOT NULL,
  `page_body` text NOT NULL,
  `page_author` varchar(255) NOT NULL,
  `page_related` varchar(255) NOT NULL,
  `page_allow_comment` char(1) NOT NULL DEFAULT '0',
  `last_update` int(10) unsigned NOT NULL,
  `page_rating` decimal(3,2) unsigned NOT NULL,
  `page_comment` int(10) unsigned NOT NULL,
  `page_list` char(1) NOT NULL,
  `page_hit` int(10) unsigned NOT NULL,
  `page_img_tmp` varchar(255) NOT NULL DEFAULT '',
  `page_attachment` varchar(255) NOT NULL DEFAULT '',
  `page_attachment_stat` int(10) unsigned NOT NULL,
  `page_pinned` char(1) NOT NULL DEFAULT '0',
  `page_status` enum('D','P','M','A','H') NOT NULL DEFAULT 'D',
  `page_template` varchar(255) NOT NULL,
  `page_mode` enum('raw','html') NOT NULL DEFAULT 'html',
  PRIMARY KEY (`page_id`),
  KEY `group_id` (`group_id`),
  KEY `cat_id` (`cat_id`),
  KEY `page_author` (`page_author`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `__PREFIX__page` (`group_id`, `cat_id`, `page_id`, `permalink`, `page_image`, `page_date`, `page_time`, `page_unix`, `page_title`, `page_keyword`, `page_body`, `page_author`, `page_related`, `page_allow_comment`, `last_update`, `page_rating`, `page_comment`, `page_list`, `page_hit`, `page_img_tmp`, `page_attachment`, `page_attachment_stat`, `page_pinned`, `page_status`, `page_template`, `page_mode`) VALUES
('GENPG', 1,  1,  'welcome.php',  '', '2011-11-11', '14:15:00', 1321017300, 'Welcome',  'add,your,keyword,here,qengine,c97net', '<p>Welcome to our site, please enjoy your stay here. If you have any question, please contact us.</p>\r\n<p>This is an example of a page, you could edit this to put information about yourself or your site so readers know where you are coming from. As mentioned before, you can create as many pages like this one.</p>\r\n<p>You can edit this text in Admin &gt; Page Manager.</p>\r\n<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent placerat eros vitae dolor pellentesque at tristique sapien vehicula. Mauris sed ligula enim, hendrerit viverra turpis. Sed pretium pharetra convallis. Fusce ac velit eget libero dapibus vehicula. Etiam ullamcorper congue odio eget porta. Praesent accumsan, dui ac condimentum congue, nisi odio auctor enim, a aliquam est enim condimentum risus. Sed in nisl placerat magna mattis auctor eu in erat.</p>\r\n<p>This is an example of a page, you could edit this to put information about yourself so readers know where you are coming from. You can create as many pages like this one.</p>\r\n<p>Aenean pellentesque metus at purus pretium sed vehicula tortor aliquam. Curabitur erat turpis, rhoncus et molestie id, pharetra non turpis. Pellentesque ultricies, urna sed lobortis tincidunt, dolor orci dapibus lectus, in aliquet ipsum sapien ac tortor. Suspendisse eu ante nibh, vel aliquam magna. Proin vel felis libero. Nullam mauris neque, suscipit sit amet placerat rutrum, vestibulum sed mauris. Sed magna nulla, tristique sit amet volutpat sed, cursus sit amet purus. Nam lobortis odio eu nunc fermentum adipiscing. Pellentesque congue ornare ipsum venenatis porta. Aenean scelerisque porttitor metus, a ornare ante rhoncus nec. Etiam metus risus, porttitor luctus iaculis sed, elementum in odio. Etiam metus leo, interdum vitae gravida sit amet, tincidunt id velit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>',  'admin',  '', '0',  1447165085, 0.00, 0,  '0',  111,  '', '', 0,  '0',  'P',  'page_default.tpl', 'html'),
('GENPG', 1,  2,  'privacy-policy.php', '', '2011-11-11', '14:30:00', 1320996600, 'Privacy Policy', '', '<h2>Information that is gathered from visitors</h2>\r\n<p>In common with other websites, log files are stored on the web server saving details such as the visitor\'s IP address, browser type, referring page and time of visit.</p>\r\n<p>Cookies may be used to remember visitor preferences when interacting with the website.</p>\r\n<p>Where registration is required, the visitor\'s email and a username will be stored on the server.</p>\r\n<h2>How the Information is used</h2>\r\n<p>The information is used to enhance the vistor\'s experience when using the website to display personalised content and possibly advertising.</p>\r\n<p>E-mail addresses will not be sold, rented or leased to 3rd parties.</p>\r\n<p>E-mail may be sent to inform you of news of our services or offers by us or our affiliates.</p>\r\n<h2>Visitor Options</h2>\r\n<p>If you have subscribed to one of our services, you may unsubscribe by following the instructions which are included in e-mail that you receive.</p>\r\n<p>You may be able to block cookies via your browser settings but this may prevent you from access to certain features of the website.</p>\r\n<h2>Cookies</h2>\r\n<p>Cookies are small digital signature files that are stored by your web browser that allow your preferences to be recorded when visiting the website. Also they may be used to track your return visits to the website.</p>\r\n<p>3rd party advertising companies may also use cookies for tracking purposes.</p>\r\n<h2>Google Ads</h2>\r\n<p>Google, as a third party vendor, uses cookies to serve ads.</p>\r\n<p>Google\'s use of the DART cookie enables it to serve ads to visitors based on their visit to sites they visit on the Internet.</p>\r\n<p>Website visitors may opt out of the use of the DART cookie by visiting the Google ad and content network privacy policy.</p>\r\n<p>(last updated March 2009)<br />Based on <a href=\"http://www.freeprivacypolicy.org/\">FPP</a></p>', 'admin',  '', '1',  1366442573, 0.00, 0,  '1',  81, '', '', 0,  '0',  'P',  'page_default.tpl', 'html'),
('GENPG', 1,  3,  'faqs.php', '', '2011-11-11', '00:00:00', 1320944400, 'FAQ&#039;s', '', '<p>Here you will find answers to many of your questions. If there is something which you cannot find the answer to, let us know and we will add your question to this list.</p>',  'admin',  '', '1',  1366442718, 0.00, 0,  '1',  15, '', '', 0,  '0',  'P',  'page_default.tpl', 'html'),
('GENPG', 1,  4,  'about-us.php', '', '2011-11-11', '00:00:00', 1320966000, 'About Us', '', '<p>Tell who you are, what you do, and anything else. Company history and the chairman will be a nice addition.</p>', 'admin',  '', '1',  1443117458, 0.00, 0,  '1',  341,  '', '', 3,  '0',  'P',  'page_default.tpl', 'html'),
('GENPG', 1,  5,  'transaction-success.php',  '', '2011-11-11', '00:00:00', 1320966000, 'Transaction Success',  '', '<p>Thank you for purchasing in our site.</p>', '', '', '0',  1473179378, 0.00, 0,  '0',  0,  '', '', 0,  '0',  'P',  '', 'html'),
('GENPG', 1,  6,  'contact-us.php', '', '2011-11-11', '00:00:00', 1320944400, 'Contact Us', '', '<p>Put your contact information here, such as office hour, parking spot, direction, etc.</p>\r\n<p>Change this text in Admin &gt; Page Manager</p>', 'admin',  '', '0',  1366442727, 0.00, 0,  '0',  0,  '', '', 0,  '0',  'P',  'page_default.tpl', 'html'),
('GENPG', 1,  7,  'terms-and-conditions.php', '', '2011-11-11', '00:00:00', 1320944400, 'Terms &amp; Conditions', '', '<p>Welcome to our website. If you continue to browse and use this website, you are agreeing to comply with and be bound by the following terms and conditions of use, which together with our privacy policy govern [business name]\'s relationship with you in relation to this website. If you disagree with any part of these terms and conditions, please do not use our website.</p>\r\n<p>The term \'[business name]\' or \'us\' or \'we\' refers to the owner of the website whose registered office is [address]. Our company registration number is [company registration number and place of registration]. The term \'you\' refers to the user or viewer of our website.</p>\r\n<p>The use of this website is subject to the following terms of use:</p>\r\n<ul>\r\n<li>The content of the pages of this website is for your general information and use only. It is subject to change without notice.</li>\r\n<li>This website uses cookies to monitor browsing preferences. If you do allow cookies to be used, the following personal information may be stored by us for use by third parties: [insert list of information].</li>\r\n<li>Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials found or offered on this website for any particular purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.</li>\r\n<li>Your use of any information or materials on this website is entirely at your own risk, for which we shall not be liable. It shall be your own responsibility to ensure that any products, services or information available through this website meet your specific requirements.</li>\r\n<li>This website contains material which is owned by or licensed to us. This material includes, but is not limited to, the design, layout, look, appearance and graphics. Reproduction is prohibited other than in accordance with the copyright notice, which forms part of these terms and conditions.</li>\r\n<li>All trade marks reproduced in this website which are not the property of, or licensed to, the operator are acknowledged on the website.</li>\r\n<li>Unauthorised use of this website may give rise to a claim for damages and/or be a criminal offence.</li>\r\n<li>From time to time this website may also include links to other websites. These links are provided for your convenience to provide further information. They do not signify that we endorse the website(s). We have no responsibility for the content of the linked website(s).</li>\r\n<li>Your use of this website and any dispute arising out of such use of the website is subject to the laws of England, Northern Ireland,&nbsp;Scotland and Wales.</li>\r\n</ul>',  'admin',  '', '1',  1366442731, 0.00, 0,  '1',  52, '', '', 0,  '0',  'P',  'page_default.tpl', 'html'),
('GENPG', 1,  8,  'powered-by-qengine.php', '', '2011-11-11', '00:00:00', 1320944400, 'Powered by qEngine', '', '<p>This site is using qEngine CMS, a simple CMS engine created by <a href=\"http://www.c97.net\">C97.net</a>. qEngine is very easy to use &amp; maintain, no need to understand PHP, and it\'s <strong>FREE!</strong> If you are interested to use this awesome script please visit <a href=\"http://www.c97.net\">www.c97.net</a> now!</p>',  'admin',  '', '1',  1366442735, 0.00, 0,  '1',  26, '', '', 0,  '0',  'P',  'page_default.tpl', 'html'),
('NEWS',  2,  9,  'news/site-is-now-up-and-ready.php',  '', '2011-11-11', '00:00:00', 1320966000, 'Site is Now Up &amp; Ready', '', '<h2>Congratulations!</h2>\r\n<p>You have succesfully installed qEngine!<br />To learn more about qEngine, please visit <a href=\"http://www.c97.net\" target=\"_blank\">www.c97.net</a>.<br /><br />(To remove this message, go to ACP &gt; Contents &gt; Manage Contents)</p>', 'admin',  '', '0',  1469804396, 0.00, 0,  '1',  94, '', '', 0,  '0',  'P',  'page_default.tpl', 'html'),
('QBANR', 0,  10, '', 'banner2.jpg',  '0000-00-00', '00:00:00', 0,  'The Banner', '#',  'This page is part of qBanner module. Please use qBanner Manager to edit this page.', '', '', '', 0,  0.00, 0,  '', 0,  '', '', 0,  '0',  'P',  '', 'html'),
('SSHOW', 0,  11, '', 'slide1.jpg', '0000-00-00', '00:00:00', 0,  'Change this content from ACP', '#',  'This page is part of SlideShow module. Please use SlideShow Manager to edit this page.', '', '', '', 0,  0.00, 0,  '', 0,  '', '', 0,  '0',  'P',  '', 'html'),
('SSHOW', 0,  12, '', 'slide2.jpg', '0000-00-00', '00:00:00', 0,  'The Mountain', '#',  'This page is part of SlideShow module. Please use SlideShow Manager to edit this page.', '', '', '', 0,  0.00, 0,  '', 0,  '', '', 0,  '0',  'P',  '', 'html'),
('SSHOW', 0,  13, '', 'slide3.jpg', '0000-00-00', '00:00:00', 0,  'The city', '#',  'This page is part of SlideShow module. Please use SlideShow Manager to edit this page.', '', '', '', 0,  0.00, 0,  '', 0,  '', '', 0,  '0',  'P',  '', 'html'),
('GENPG', 1,  14, 'backlinking-instructions.php', '', '2017-04-01', '18:10:00', 1491063000, 'Backlinking Instructions', '', '<p>This web site may need your listing to have a backlink to this web site. Please add the following code to your web site:</p>\r\n<pre>{qemod:ke_core:backlink}</pre>\r\n<p>Replace [user_id] with your user ID. If you are already logged in, simply copy the code. Please don\'t change the code, or we can not validate your backlink.</p>\r\n<p>After you add the code, please update your listings.</p>\r\n<p>PS: for administrator, if your web site doesn\'t need any backlinking, you may want to remove this information. You can change the backlink code in ACP - Settings.</p>',  'admin',  '', '1',  1491063767, 0.00, 0,  '1',  18, '', '', 0,  '0',  'P',  'page_default.tpl', 'html');

DROP TABLE IF EXISTS `__PREFIX__page_cat`;
CREATE TABLE `__PREFIX__page_cat` (
  `idx` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `group_id` varchar(5) NOT NULL,
  `parent_id` int(10) unsigned NOT NULL,
  `permalink` varchar(255) NOT NULL,
  `cat_name` varchar(255) NOT NULL,
  `cat_details` text NOT NULL,
  `cat_image` varchar(255) NOT NULL,
  PRIMARY KEY (`idx`),
  KEY `group_id` (`group_id`),
  KEY `parent_id` (`parent_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `__PREFIX__page_cat` (`idx`, `group_id`, `parent_id`, `permalink`, `cat_name`, `cat_details`, `cat_image`) VALUES
(1, 'GENPG',  0,  'general-pages.php',  'General Pages',  '<p>General Pages</p>', ''),
(2, 'NEWS', 0,  'news.php', 'General News', '<p>General News</p>',  '');

DROP TABLE IF EXISTS `__PREFIX__page_group`;
CREATE TABLE `__PREFIX__page_group` (
  `idx` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `group_id` varchar(5) NOT NULL,
  `group_title` varchar(255) NOT NULL,
  `group_notes` varchar(255) NOT NULL,
  `all_cat_list` char(1) NOT NULL,
  `cat_list` char(1) NOT NULL,
  `page_cat` char(1) NOT NULL,
  `page_image` char(1) NOT NULL,
  `page_image_size` int(10) unsigned NOT NULL,
  `page_thumb` int(10) unsigned NOT NULL,
  `page_gallery` char(1) NOT NULL,
  `page_gallery_thumb` int(10) unsigned NOT NULL,
  `page_author` char(1) NOT NULL,
  `page_comment` varchar(15) NOT NULL,
  `page_attachment` char(1) NOT NULL,
  `page_date` char(1) NOT NULL,
  `page_folder` varchar(25) NOT NULL,
  `page_sort` enum('t','d') NOT NULL DEFAULT 't',
  `hidden_private` char(1) NOT NULL,
  `group_template` varchar(255) NOT NULL,
  `page_template` varchar(255) NOT NULL,
  PRIMARY KEY (`idx`),
  KEY `group_id` (`group_id`),
  KEY `hidden_private` (`hidden_private`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `__PREFIX__page_group` (`idx`, `group_id`, `group_title`, `group_notes`, `all_cat_list`, `cat_list`, `page_cat`, `page_image`, `page_image_size`, `page_thumb`, `page_gallery`, `page_gallery_thumb`, `page_author`, `page_comment`, `page_attachment`, `page_date`, `page_folder`, `page_sort`, `hidden_private`, `group_template`, `page_template`) VALUES
(1, 'GENPG',  'Common Page',  'General pages, eg: company history, about you, etc. (please do NOT remove this content type, you can edit this message in ACP &gt; Contents &gt; Manage Types)', '1',  '1',  '1',  '1',  500,  100,  '1',  200,  '1',  'pagecomment',  '0',  '0',  '', 't',  '0',  'body_default.tpl', 'page_default.tpl'),
(2, 'NEWS', 'News', 'Site news (please do NOT remove this content type, you can edit this message in ACP &gt; Contents &gt; Manage Types)', '1',  '1',  '1',  '1',  400,  100,  '0',  0,  '0',  '0',  '0',  '1',  'news', 't',  '0',  'body_news.tpl',  '_blank'),
(3, 'QBANR',  'qBanner',  'qBanner module storage', '0',  '0',  '0',  '1',  0,  0,  '0',  0,  '0',  '0',  '', '0',  '', 't',  '1',  'body_default.tpl', 'page_default.tpl'),
(4, 'SSHOW',  'Slideshow',  'Slideshow module storage', '0',  '0',  '0',  '1',  0,  0,  '0',  0,  '0',  '0',  '', '0',  '', 't',  '1',  'body_default.tpl', 'page_default.tpl');

DROP TABLE IF EXISTS `__PREFIX__payment_log`;
CREATE TABLE `__PREFIX__payment_log` (
  `log_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `log_time` int(10) unsigned NOT NULL,
  `pay_type` varchar(20) NOT NULL,
  `order_id` varchar(16) NOT NULL,
  `txn_id` varchar(32) NOT NULL,
  `order_total` decimal(10,2) NOT NULL,
  `order_paid` decimal(10,2) NOT NULL,
  `sent_request` text NOT NULL,
  `response` text NOT NULL,
  `payment_status` char(1) NOT NULL,
  `notes` text NOT NULL,
  PRIMARY KEY (`log_id`),
  KEY `order_id` (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `__PREFIX__permalink`;
CREATE TABLE `__PREFIX__permalink` (
  `idx` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `url` varchar(255) NOT NULL,
  `target_script` varchar(255) NOT NULL,
  `target_idx` varchar(255) NOT NULL,
  `target_param` varchar(255) NOT NULL,
  PRIMARY KEY (`idx`),
  KEY `url` (`url`),
  KEY `target_script` (`target_script`),
  KEY `target_idx` (`target_idx`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `__PREFIX__permalink` (`idx`, `url`, `target_script`, `target_idx`, `target_param`) VALUES
(1, 'welcome.php',  'page.php', '1',  ''),
(2, 'privacy-policy.php', 'page.php', '2',  ''),
(3, 'faqs.php', 'page.php', '3',  ''),
(4, 'about-us.php', 'page.php', '4',  ''),
(5, 'contact-us.php', 'page.php', '6',  ''),
(6, 'terms-and-conditions.php', 'page.php', '7',  ''),
(7, 'powered-by-qengine.php', 'page.php', '8',  ''),
(8, 'news/site-is-now-up-and-ready.php',  'page.php', '9',  ''),
(9, 'general-pages.php',  'page.php', '1',  'list'),
(10,  'news.php', 'page.php', '2',  'list'),
(11,  'transaction-success.php',  'page.php', '5',  ''),
(12,  'general-directory.php',  'index.php',  '1',  'dir'),
(13,  'category/default-category.php',  'listing_search.php', '1',  'cmd=list'),
(14,  'example-listing.php',  'detail.php', '1',  ''),
(15,  'backlinking-instructions.php', 'page.php', '14', '');

DROP TABLE IF EXISTS `__PREFIX__qadmin_log`;
CREATE TABLE `__PREFIX__qadmin_log` (
  `log_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `log_date` int(10) unsigned NOT NULL,
  `log_file` varchar(255) NOT NULL,
  `log_table` varchar(255) NOT NULL,
  `log_user` varchar(255) NOT NULL,
  `log_ip` varchar(45) NOT NULL,
  `log_pid` varchar(255) NOT NULL,
  `log_title` varchar(255) NOT NULL,
  `log_action` int(10) unsigned NOT NULL,
  `log_previous` text NOT NULL,
  `log_now` text NOT NULL,
  PRIMARY KEY (`log_id`),
  KEY `log_ip` (`log_ip`),
  KEY `log_user` (`log_user`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `__PREFIX__qcomment`;
CREATE TABLE `__PREFIX__qcomment` (
  `comment_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `mod_id` varchar(255) NOT NULL DEFAULT '',
  `item_id` varchar(80) NOT NULL,
  `item_title` varchar(255) NOT NULL,
  `item_url` varchar(255) NOT NULL,
  `comment_user` varchar(255) NOT NULL DEFAULT '',
  `comment_title` varchar(255) NOT NULL DEFAULT '',
  `comment_body` text NOT NULL,
  `comment_date` date NOT NULL DEFAULT '0000-00-00',
  `comment_rate` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `comment_helpful` varchar(16) NOT NULL,
  `comment_approve` char(1) NOT NULL DEFAULT '',
  PRIMARY KEY (`comment_id`),
  KEY `mod_id` (`mod_id`),
  KEY `item_id` (`item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='No comment!';


DROP TABLE IF EXISTS `__PREFIX__qcomment_set`;
CREATE TABLE `__PREFIX__qcomment_set` (
  `group_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `comment_mode` char(1) NOT NULL,
  `comment_approval` char(1) NOT NULL,
  `member_only` char(1) NOT NULL,
  `unique_comment` char(1) NOT NULL,
  `comment_helpful` char(1) NOT NULL,
  `comment_on_comment` char(1) NOT NULL,
  `captcha` char(1) NOT NULL,
  `detail` char(1) NOT NULL,
  `mod_id` varchar(15) NOT NULL,
  `notes` varchar(255) NOT NULL,
  PRIMARY KEY (`group_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `__PREFIX__qcomment_set` (`group_id`, `comment_mode`, `comment_approval`, `member_only`, `unique_comment`, `comment_helpful`, `comment_on_comment`, `captcha`, `detail`, `mod_id`, `notes`) VALUES
(1, '2',  '0',  '0',  '0',  '0',  '1',  '0',  '0',  'conc', 'Comments on comments'),
(3, '2',  '1',  '0',  '0',  '0',  '1',  '0',  '1',  'pagecomment',  'Page Comment'),
(4, '3',  '1',  '1',  '1',  '1',  '1',  '1',  '1',  'listing',  'Listing Reviews');

DROP TABLE IF EXISTS `__PREFIX__stats_daily`;
CREATE TABLE `__PREFIX__stats_daily` (
  `stats_date` date NOT NULL,
  `stats_hit` int(10) unsigned NOT NULL,
  `stats_visit` int(10) unsigned NOT NULL,
  PRIMARY KEY (`stats_date`),
  KEY `stats_hit` (`stats_hit`),
  KEY `stats_visit` (`stats_visit`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `__PREFIX__stats_ip`;
CREATE TABLE `__PREFIX__stats_ip` (
  `ip_address` varchar(15) NOT NULL,
  `last_update` int(10) unsigned NOT NULL,
  PRIMARY KEY (`ip_address`),
  KEY `last_update` (`last_update`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `__PREFIX__user`;
CREATE TABLE `__PREFIX__user` (
  `user_id` varchar(80) NOT NULL DEFAULT '',
  `user_passwd` varchar(255) NOT NULL DEFAULT '',
  `user_email` varchar(255) NOT NULL DEFAULT '',
  `user_level` char(1) NOT NULL DEFAULT '1',
  `user_since` date NOT NULL DEFAULT '0000-00-00',
  `admin_level` char(1) NOT NULL DEFAULT '0',
  `reset_passwd` varchar(16) NOT NULL DEFAULT '',
  `user_activation` varchar(16) NOT NULL DEFAULT '',
  `axsrf_token` varchar(32) NOT NULL,
  `user_notes` text NOT NULL,
  `user_fave` text NOT NULL,
  `user_refer_history` text NOT NULL,
  `user_refer_num` int(10) unsigned NOT NULL,
  PRIMARY KEY (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT=' Member profile & billing address';
